import type { FieldSchema } from '../types';

const PROFESIONES = [
  'Abogado','Administrador','Administrativo','Arquitecto','Biólogo','Carabinero',
  'Comunicador Audiovisual','Comunicador Social','Constructor Civil','Contado Auditor',
  'Economista','Empresario','Enfermera','Fuerza Aerea','Ing. Civil','Ing. Comercial',
  'Ing. Ejecución','Licenciado','Médico','Militar','Nutricionista','Obstetricia',
  'Otros','Paramedico','Profesor','Psicólogo','Publicista','Secretaria',
  'Sociólogo','Trabajador Social','Academico(a)','Administración de Aeropuerto',
  'Administración de Empresas','Administración de RR.HH','Administración Hotelera',
  'Administrador(a) Comercial','Administrador(a) de Empresas','Administrador(a) de Red',
  'Administrador(a) Institucional','Administrador(a) Público','Administrativo Bancario',
  'Aernáutica','Agente Comercial','Agente Corporativo','Agente de Oficina','Agente de Viaje',
  'Agricultor(a)','Agrónomo','Analista','Analista Contable','Analista Ctas. Corrientes',
  'Analista de Crédito','Alanista de Operación','Analista de Sistemas',
  'Analista Programador(a)','Analaista Químico','Antropólogo(a)','Arsenalero(a)',
  'Arsenalero(a) Quirúrgica','Aresano(a)','Asesor(a) de Crédito Hipotecario',
  'Asesor(a) Educacional','Asesor(a) en Dibujo Técnico','Asesor(a) en Ventas',
  'Asesor(a) Juridico','Asesora del Hogar','Asesoria Cosmetologica',
  'Asistente Administrativo','Asistente Cobranzas','Asistente Comercial',
  'Asistente Contable','Asistente de Enfermería','Asistente de Gerencia',
  'Asistente de Párvulos','Asistente de Remuneraciones','Asistente de Servicio',
  'Asistente de Ventas','Asistente Dental','Asistente Jurídico','Asistente Legal',
  'Asistente Previcional','Asistente RR.HH','Asistente Social','Asistente Telefónico',
  'Astronóni(a)','Auditor(a)','Auxiliar de Enfermería','Auxiliar de Farmacia',
  'Auxiliar de Piso','Auxiliar de Vuelo','Auxiliar Paramédico','Auxiliar Técnico de Farmacia',
  'Ayudante Contador','Back Office','Bailarín(a) Clásico','Bancario(a)','Bibliotecario(a)',
  'Bioquímico(a)','Biotecnologo Dental(a)','Bodeguero(a)','Cajero Administrativo(a)',
  'Cajero Bancario(a)','Cajero Vendedor(a)','Cajero(a)','Camarero','Cartero','Chef',
  'Chofer','Cirujano Dentista','Comerciante','Comerciante Agricultor',
  'Comerciante Independiente','Comercio Exterior','Comunicador Multimedia','Conductor(a)',
  'Conductor(a) Buses','Conductor(a) de Televisión','Conductor(a) Metro',
  'Consejera de Clientes','Consultor(a)','Consultor(a) Informático','Controlador',
  'Contratista','Control de Calidad','Control Industrial','Controlador(a) de Transito Áereo',
  'Coordinador(a)','Coordinador(a) de Post Venta','Coordinador(a) de RR.HH',
  'Coordinador(a) General','Corredor de Propiedades','Corredor de Seguros',
  'Cosmetólogo(a)','Decorador(a) de Interior','Dentista','Detective','Dibujante',
  'Dibujante Arquitectónico','Dibujante en Obras Civiles','Dibujante Gráfico',
  'Dibujante Proyectista','Dibujante Técnico','Dirección y Producción de TV',
  'Diseñador(a)','Diseñador(a) Gráfico','Diseñador(a) de Vestuario',
  'Diseñador(a) Industrial','Educadora de Párvulos','Educadora Diferencial',
  'Eléctrico Mecánico','Empleado Fuerzas Armadas','Escritor(a)','Esteticista',
  'Estilista','Estudiante Universitario','Fonoaudiologo(a)','Fotógrafo',
  'Funcionario(a) Publico','Funcionario(a) Judicial','Garzón(a)','Gastronomia',
  'Gendarme','General de Carabinero en Retiro','Geógrafo','Geólogo','Gerente',
  'Gerente Zonal','Gerente(a) de Finanzas','Guardia','Hotelero(a)',
  'Importación y Exportación','Independiente','Interprete','Informático(a)',
  'Ing. Agricola','Ingeniero(a)','Ing. Acuicultor','Ing. Aeronautico','Ing. Agrónomo',
  'Ing. Ambiental','Ing. Automatización','Img. Civil Eléctrico','Ing. Civil en Computación',
  'Ing. Civil en Minas','Ing. Civil Industrial','Ing. Civil Informático','Ing. Civil Mecánico',
  'Ing. Civil Obras Civiles','Ing. Civil Químico','Ing. Construcción','Ing.En Administración',
  'Ing. en Alimentos','Ing. en Comercio','Ing. en Computación','Ing. en Construcción',
  'Ing. en Prevención','Ing. en Sistemas','Ing. en Sonido','Ing. en Telecomunicaciones',
  'Ing. en Turismo','Ing. Estadistico','Ing. Finanzas','Ing. Forestal','Kinesiólogo',
  'Licenciado(a) en Artes','Licenciado(a) en Educación','Licenciado(a) en Historia',
  'Licenciado(a) en Lengua y Literatura','Marino Mercante','Matron(a)',
  'Mecánico Automoriz','Mecánico Industrial','Médico Cirujano',
  'Médico Cirujano - Traumatólogo(a)','Médico Dermatólogo(a)','Médico General',
  'Médico Naraucanacirujano(a)','Médico Radiólogo(a)','Médico Traumatólogo',
  'Meteorólogo','Modelo','Músico','Oficial de Ejército','Oficial de Gendarmería',
  'Oficial de Marina','Oficial Fach','Operador','Operador Maq. Pesada','Operario(a)',
  'Paramédico(a)','Peluquero(a)','Piloto Comercial','Prevensionista','Procurador',
  'Profesional Técnico','Psicopedagogo(a)','Psiquiatra','Químico Analista',
  'Químico Nuclear','Recaudador(a)','Relacionador Público','Secretaria','Sobrecargo',
  'Técnico Administración de Empresas','Técnico Administrativo','Técnico Agrícola',
  'Técnico Agropecuario','Técnico Automotriz','Técnico Eléctrico',
  'Técnico en Automatización','Técnico en Ciencias Criminalistica',
  'Técnico en Computación','Técnico en Construcción','Técnico en Diseño Publicitario',
  'Técnico en Educación Parvularia','Técnico en Electrónica Industrial',
  'Técnico en Enfermería','Técnico en Gastronomía','Técnico en Mantención',
  'Técnico en Marketing','Técnico en Sonido','Técnico en Turismo','Técnico Financiero',
  'Técnico Forestal','Técnico Gráfico','Técnico Informático','Tecnologo Medico',
  'Terapeuta Familiar','Terapeuta Ocupacional','Tesorero(a)','Tipógrafo',
  'Traductor','Transportista','Transportista Escolar','Tripulante de Cabina',
].sort();

const NACIONALIDADES = [
  'Chileno/a','Afgano/na','Albanés/sa','Alemán/na','Andorrano/na','Angoleño/ña',
  'Antiguano/na','Argelino/na','Argentino/a','Armenio/nia','Australiano/na',
  'Austriaco/ca','Azerbaiyano/na','Bahameño/ña','Bangladesí','Barbadense','Bareiní',
  'Belga','Beliceño/ña','Beninés/sa','Bielorruso/sa','Birmano/na','Boliviano/a',
  'Bosnio/nia','Botsuano/na','Brasileño/a','Británico/ca','Bruneano/na','Búlgaro/ra',
  'Burkinés','Burundés/sa','Butanés/sa','Caboverdiano/na','Camboyano/na',
  'Camerunés/sa','Canadiense','Catarí','Ceilanés/sa','Centroafricano/na','Chadiano/na',
  'Checo/ca','Chino/na','Chipriota','Colombiano/a','Comorense','Congoleño/ña',
  'Costarricense','Cristobaleño/ña','Croata','Cubano/a','Danés/sa','Dominicano/na',
  'Dominiqués','Ecuatoguineano/na','Ecuatoriano/a','Egipcio/cia','Emiratí','Eritreo/a',
  'Eslovaco/ca','Esloveno/na','Español/la','Estadounidense','Estonio/nia','Etíope',
  'Filipino/na','Finlandés/sa','Fiyiano/na','Francés/sa','Gabonés/sa','Gambiano/na',
  'Georgiano/na','Ghanés/sa','Granadino/a','Griego/ga','Guatemalteco/a','Guineano/na',
  'Guyanés/esa','Haitiano/a','Hondureño/a','Húngaro/ra','Indio/dia','Indonesio/sia',
  'Iraní','Iraquí','Irlandés/sa','Islandés/sa','Israelí','Italiano/na',
  'Jamaicano/na o Jamaiquino/na','Japonés/sa','Jordano/na','Kazajo/ja','Keniano/na',
  'Kirguís','Kiribatiano/na','Kuwaití','Laosiano/na','Lesotense','Letón/na',
  'Libanés/sa','Liberiano/na','Libio/a','liechtensteiniano/na','Lituano/na',
  'Luxemburgués/sa','Macedonio/nia','Malasio/sia','Malauí','Maldivo/va','Malgache',
  'Maliense, Malí','Maltés/sa','Marfileño/ña','Marroquí','Marshalés/sa',
  'Mauriciano/na','Mauritano/na','Mexicano/a','Micronesio/sia','Moldavo/va',
  'Monegasco/ca','Mongol/la','Montenegrino/na','Mozambiqueño/ña','Namibio/bia',
  'Nauruano/na','Neerlandés/sa','Neozelandés/sa','Nepalés/sa','Nicaragüense',
  'Nigeriano /na','Nigerino/na','Norcoreano/na','Noruego/ga','Omaní','Pakistaní',
  'Palauano/na','Palestino/na','Panameño/ña','Papú','Paraguayo/a','Peruano/a',
  'Polaco/ca','Portugués/sa','Ruandés/sa','Rumano/na','Ruso/sa','Salomonense',
  'Salvadoreño/ña','Samoano/na','Sanmarinense','Santalucense','Santotomense',
  'Sanvicentino/na','Saudí o saudita','Senegalés/sa','Serbio/a','Seychellense',
  'Sierraleonés/sa','Singapurense','Sirio/ria','Somalí','Suazi','Sudafricano/na',
  'Sudanés/sa','Sueco/ca','Suizo/za','Surcoreano/na','Surinamés/esa','Sursudanés/sa',
  'Tailandés/sa','Tanzano/na','Tayiko/ka','Timorense','Togolés/sa','Tongano/na',
  'Trinitense','Tunecino/na','Turco/ca','Turcomano/na','Tuvaluano/na','Ucraniano/na',
  'Ugandés/sa','Uruguayo/a','Uzbeko/ka','Vanuatuense','Vaticano/na','Venezolano/a',
  'Vietnamita','Yemení','Yibutiano/na','Zambiano/na','Zimbabuense',
];

export function getFieldSchema(): FieldSchema {
  return {
    inmobiliaria: 'araucana',
    fields: [
      { key: 'rut',             label: 'RUT',                type: 'rut',  required: true },
      { key: 'nombres',         label: 'Nombres',            type: 'text', required: true },
      { key: 'apellidoPaterno', label: 'Apellido paterno',   type: 'text', required: true },
      { key: 'apellidoMaterno', label: 'Apellido materno',   type: 'text', required: false },
      { key: 'telefonoCelular', label: 'Teléfono celular',   type: 'text', required: true,
        helpText: 'Formato: 9XXXXXXXX (9 dígitos, sin +56)' },
      { key: 'correoElectronico', label: 'Correo electrónico', type: 'text', required: true },
      {
        key: 'region',
        label: 'Región',
        type: 'select',
        required: true,
        options: [
          { value: 'Arica y Parinacota',                                    label: 'Arica y Parinacota' },
          { value: 'Tarapacá',                                               label: 'Tarapacá' },
          { value: 'Antofagasta',                                            label: 'Antofagasta' },
          { value: 'Atacama',                                                label: 'Atacama' },
          { value: 'Coquimbo',                                               label: 'Coquimbo' },
          { value: 'Valparaíso',                                             label: 'Valparaíso' },
          { value: 'Región del Libertador Gral. Bernardo O\'Higgins',        label: 'Región del Libertador Gral. Bernardo O\'Higgins' },
          { value: 'Región del Maule',                                       label: 'Región del Maule' },
          { value: 'Región de Ñuble',                                        label: 'Región de Ñuble' },
          { value: 'Región del Biobío',                                      label: 'Región del Biobío' },
          { value: 'Región de la Araucanía',                                 label: 'Región de la Araucanía' },
          { value: 'Región de los Ríos',                                     label: 'Región de los Ríos' },
          { value: 'Región de los Lagos',                                    label: 'Región de los Lagos' },
          { value: 'Región Aisén del Gral. Carlos Ibañez del Campo',         label: 'Región Aisén del Gral. Carlos Ibañez del Campo' },
          { value: 'Región de Magallanes y de la Antártica Chilena',         label: 'Región de Magallanes y de la Antártica Chilena' },
          { value: 'Región Metropolitana de Santiago',                       label: 'Región Metropolitana de Santiago' },
        ],
      },
      { key: 'ciudad',  label: 'Provincia / Ciudad', type: 'text', required: true,
        helpText: 'Ej: Santiago, Cordillera, Chacabuco, Maipo, Mellipilla, Talagante' },
      { key: 'comuna',  label: 'Comuna',             type: 'text', required: true },
      { key: 'direccion', label: 'Dirección y número', type: 'text', required: true,
        helpText: 'Ej: Av. Providencia 1234' },
      { key: 'fechaNacimiento', label: 'Fecha de nacimiento', type: 'text', required: true,
        helpText: 'Formato DD/MM/AAAA' },
      {
        key: 'genero',
        label: 'Sexo',
        type: 'select',
        required: true,
        options: [
          { value: 'Masculino', label: 'Masculino' },
          { value: 'Femenino',  label: 'Femenino'  },
          { value: 'Otro',      label: 'Otro'       },
        ],
      },
      {
        key: 'profesion',
        label: 'Profesión',
        type: 'select',
        required: true,
        options: PROFESIONES.map(p => ({ value: p, label: p })),
      },
      {
        key: 'nacionalidad',
        label: 'Nacionalidad',
        type: 'select',
        required: true,
        options: NACIONALIDADES.map(n => ({ value: n, label: n })),
      },
      {
        key: 'mediaOrigen',
        label: 'Medio de origen',
        type: 'select',
        required: true,
        options: [
          { value: 'Migración',           label: 'Migración' },
          { value: 'Folleto',             label: 'Folleto' },
          { value: 'Radio',               label: 'Radio' },
          { value: 'Televisión',          label: 'Televisión' },
          { value: 'Mensaje de Texto',    label: 'Mensaje de Texto' },
          { value: 'Llamada Telefónica',  label: 'Llamada Telefónica' },
          { value: 'Instagram',           label: 'Instagram' },
          { value: 'Facebook',            label: 'Facebook' },
          { value: 'Portal Inmobiliario', label: 'Portal Inmobiliario' },
          { value: 'Toc toc',             label: 'Toc toc' },
          { value: 'Letrero',             label: 'Letrero' },
          { value: 'Papeleta',            label: 'Papeleta' },
          { value: 'Zaror Invest',        label: 'Zaror Invest' },
          { value: 'Capital Inteligente', label: 'Capital Inteligente' },
          { value: 'Live And Invest',     label: 'Live And Invest' },
        ],
      },
    ],
  };
}
