import type { FieldSchema } from '../types';

const COMUNAS = [
  'Arica','Camarones','Putre','General Lagos',
  'Iquique','Alto Hospicio','Pozo Almonte','Camiña','Colchane','Huara','Pica',
  'Antofagasta','Mejillones','Sierra Gorda','Taltal','Calama','Ollagüe','San Pedro de Atacama','Tocopilla','María Elena',
  'Copiapó','Caldera','Tierra Amarilla','Chañaral','Diego de Almagro','Vallenar','Alto del Carmen','Freirina','Huasco',
  'La Serena','Coquimbo','Andacollo','La Higuera','Paiguano','Vicuña','Illapel','Canela','Los Vilos','Salamanca','Ovalle','Combarbalá','Monte Patria','Punitaqui','Río Hurtado',
  'Valparaíso','Casablanca','Concón','Juan Fernández','Puchuncaví','Quintero','Viña del Mar','Isla de Pascua','Los Andes','Calle Larga','Rinconada','San Esteban','La Ligua','Cabildo','Papudo','Petorca','Zapallar','Quillota','Calera','Hijuelas','La Cruz','Nogales','San Antonio','Algarrobo','Cartagena','El Quisco','El Tabo','Santo Domingo','San Felipe','Catemu','Llaillay','Panquehue','Putaendo','Santa María','Quilpué','Limache','Olmué','Villa Alemana',
  'Santiago','Cerrillos','Cerro Navia','Conchalí','El Bosque','Estación Central','Huechuraba','Independencia','La Cisterna','La Florida','La Granja','La Pintana','La Reina','Las Condes','Lo Barnechea','Lo Espejo','Lo Prado','Macul','Maipú','Ñuñoa','Pedro Aguirre Cerda','Peñalolén','Providencia','Pudahuel','Quilicura','Quinta Normal','Recoleta','Renca','San Joaquín','San Miguel','San Ramón','Vitacura','Puente Alto','Pirque','San José de Maipo','Colina','Lampa','Tiltil','San Bernardo','Buin','Calera de Tango','Paine','Melipilla','Alhué','Curacaví','María Pinto','San Pedro','Talagante','El Monte','Isla de Maipo','Padre Hurtado','Peñaflor',
  'Rancagua','Codegua','Coinco','Coltauco','Doñihue','Graneros','Las Cabras','Machalí','Malloa','Mostazal','Olivar','Peumo','Pichidegua','Quinta de Tilcoco','Rengo','Requínoa','San Vicente','Pichilemu','La Estrella','Litueche','Marchihue','Navidad','Paredones','San Fernando','Chépica','Chimbarongo','Lolol','Nancagua','Palmilla','Peralillo','Placilla','Pumanque','Santa Cruz',
  'Talca','Constitución','Curepto','Empedrado','Maule','Pelarco','Pencahue','Río Claro','San Clemente','San Rafael','Cauquenes','Chanco','Pelluhue','Curicó','Hualañé','Licantén','Molina','Rauco','Romeral','Sagrada Familia','Teno','Vichuquén','Linares','Colbún','Longaví','Parral','Retiro','San Javier','Villa Alegre','Yerbas Buenas',
  'Chillán','Bulnes','Chillán Viejo','El Carmen','Pemuco','Pinto','Quillón','San Ignacio','Yungay','Cobquecura','Coelemu','Ninhue','Portezuelo','Quirihue','Ránquil','Treguaco','Coihueco','Ñiquén','San Carlos','San Fabián','San Nicolás',
  'Concepción','Coronel','Chiguayante','Florida','Hualqui','Lota','Penco','San Pedro de la Paz','Santa Juana','Talcahuano','Tomé','Hualpén','Lebu','Arauco','Cañete','Contulmo','Curanilahue','Los Álamos','Tirúa','Los Ángeles','Antuco','Cabrero','Laja','Mulchén','Nacimiento','Negrete','Quilaco','Quilleco','San Rosendo','Santa Bárbara','Tucapel','Yumbel','Alto Biobío',
  'Temuco','Carahue','Cunco','Curarrehue','Freire','Galvarino','Gorbea','Lautaro','Loncoche','Melipeuco','Nueva Imperial','Padre Las Casas','Perquenco','Pitrufquén','Pucón','Saavedra','Teodoro Schmidt','Toltén','Vilcún','Villarrica','Cholchol','Angol','Collipulli','Curacautín','Ercilla','Lonquimay','Los Sauces','Lumaco','Purén','Renaico','Traiguén','Victoria',
  'Valdivia','Corral','Futrono','La Unión','Lago Ranco','Lanco','Los Lagos','Máfil','Mariquina','Paillaco','Panguipulli','Río Bueno',
  'Puerto Montt','Calbuco','Cochamó','Fresia','Frutillar','Los Muermos','Llanquihue','Maullín','Puerto Varas','Castro','Ancud','Chonchi','Curaco de Vélez','Dalcahue','Puqueldón','Queilén','Quellón','Quemchi','Quinchao','Osorno','Puerto Octay','Purranque','Puyehue','Río Negro','San Juan de la Costa','San Pablo','Chaitén','Futaleufú','Hualaihué','Palena',
  'Coyhaique','Lago Verde','Aysén','Cisnes','Guaitecas','Cochrane','O\'Higgins','Tortel','Chile Chico','Río Ibáñez',
  'Punta Arenas','Laguna Blanca','Río Verde','San Gregorio','Cabo de Hornos','Antártica','Porvenir','Primavera','Timaukel','Puerto Natales','Torres del Paine',
].sort();

export function getFieldSchema(): FieldSchema {
  return {
    inmobiliaria: 'danacorp',
    fields: [
      { key: 'rut',               label: 'RUT',                 type: 'rut',   required: true },
      { key: 'apellidoPaterno',   label: 'Apellido paterno',    type: 'text',  required: true },
      { key: 'apellidoMaterno',   label: 'Apellido materno',    type: 'text',  required: true },
      { key: 'nombres',           label: 'Nombres',             type: 'text',  required: true },
      {
        key: 'genero',
        label: 'Género',
        type: 'select',
        required: true,
        options: [
          { value: 'Masculino', label: 'Masculino' },
          { value: 'Femenino',  label: 'Femenino'  },
        ],
      },
      {
        key: 'fechaNacimiento',
        label: 'Fecha de nacimiento',
        type: 'text',
        required: true,
        helpText: 'Formato DD-MM-AAAA',
      },
      {
        key: 'estadoCivil',
        label: 'Estado civil',
        type: 'select',
        required: true,
        options: [
          { value: 'Soltero',           label: 'Soltero/a'         },
          { value: 'Casado',            label: 'Casado/a'          },
          { value: 'Divorciado',        label: 'Divorciado/a'      },
          { value: 'Viudo',             label: 'Viudo/a'           },
          { value: 'Conviviente Civil', label: 'Conviviente civil' },
        ],
      },
      { key: 'nacionalidad',      label: 'Nacionalidad',        type: 'text',  required: true },
      { key: 'profesion',         label: 'Profesión',           type: 'text',  required: true },
      { key: 'telefonoCelular',   label: 'Teléfono celular',    type: 'phone', required: true },
      { key: 'correoElectronico', label: 'Correo electrónico',  type: 'email', required: true },
      { key: 'direccion',         label: 'Dirección',           type: 'text',  required: true, helpText: 'Calle y número (ej: Av. Providencia 1234)' },
      {
        key: 'region',
        label: 'Región',
        type: 'select',
        required: true,
        options: [
          { value: 'Región de Arica y Parinacota',                        label: 'Región de Arica y Parinacota'                        },
          { value: 'Región de Tarapacá',                                  label: 'Región de Tarapacá'                                  },
          { value: 'Región de Antofagasta',                               label: 'Región de Antofagasta'                               },
          { value: 'Región de Atacama',                                   label: 'Región de Atacama'                                   },
          { value: 'Región de Coquimbo',                                  label: 'Región de Coquimbo'                                  },
          { value: 'Región de Valparaíso',                                label: 'Región de Valparaíso'                                },
          { value: 'Región Metropolitana de Santiago',                    label: 'Región Metropolitana de Santiago'                    },
          { value: "Región del Libertador General Bernardo O'Higgins",    label: "Región del Libertador General Bernardo O'Higgins"    },
          { value: 'Región del Maule',                                    label: 'Región del Maule'                                   },
          { value: 'Región de Ñuble',                                     label: 'Región de Ñuble'                                     },
          { value: 'Región del Biobío',                                   label: 'Región del Biobío'                                   },
          { value: 'Región de La Araucanía',                              label: 'Región de La Araucanía'                              },
          { value: 'Región de Los Ríos',                                  label: 'Región de Los Ríos'                                  },
          { value: 'Región de Los Lagos',                                 label: 'Región de Los Lagos'                                 },
          { value: 'Región de Aysén del General Carlos Ibáñez del Campo', label: 'Región de Aysén del General Carlos Ibáñez del Campo' },
          { value: 'Región de Magallanes y de la Antártica Chilena',      label: 'Región de Magallanes y de la Antártica Chilena'      },
        ],
      },
      {
        key: 'comuna',
        label: 'Comuna',
        type: 'select',
        required: true,
        options: COMUNAS.map((c) => ({ value: c, label: c })),
      },
      { key: 'ciudad',     label: 'Ciudad',    type: 'text',           required: true },
      { key: 'proyecto',   label: 'Proyecto',  type: 'cascade-parent', required: true },
      { key: 'unidad',     label: 'Unidad',    type: 'cascade-child',  required: true },
      { key: 'tipologia',  label: 'Tipología', type: 'cascade-auto',   required: true },
    ],
  };
}
