import type { FieldSchema } from '../types';

export function getFieldSchema(): FieldSchema {
  return {
    inmobiliaria: 'euro',
    fields: [
      { key: 'rut',              label: 'RUT',                type: 'rut',   required: true },
      { key: 'apellidoPaterno',  label: 'Apellido paterno',   type: 'text',  required: true },
      { key: 'apellidoMaterno',  label: 'Apellido materno',   type: 'text',  required: true },
      { key: 'nombres',          label: 'Nombres',            type: 'text',  required: true },
      {
        key: 'genero',
        label: 'Género',
        type: 'select',
        required: true,
        options: [
          { value: 'Masculino', label: 'Masculino' },
          { value: 'Femenino',  label: 'Femenino'  },
        ],
      },
      {
        key: 'fechaNacimiento',
        label: 'Fecha de nacimiento',
        type: 'text',
        required: true,
        helpText: 'Formato DD-MM-AAAA',
      },
      { key: 'nacionalidad',     label: 'Nacionalidad',       type: 'text',  required: true },
      {
        key: 'profesion',
        label: 'Profesión',
        type: 'select',
        required: true,
        options: [
          { value: 'ABOGADO', label: 'ABOGADO' },
          { value: 'ACADÉMICO(A)', label: 'ACADÉMICO(A)' },
          { value: 'ACUPUNTOR', label: 'ACUPUNTOR' },
          { value: 'ACTOR', label: 'ACTOR' },
          { value: 'ADMINISTRACIÓN', label: 'ADMINISTRACIÓN' },
          { value: 'ADMINISTRACIÓN DE AEROPUERTO', label: 'ADMINISTRACIÓN DE AEROPUERTO' },
          { value: 'ADMINISTRACIÓN DE EMPRESAS', label: 'ADMINISTRACIÓN DE EMPRESAS' },
          { value: 'ADMINISTRACIÓN EN RR.HH', label: 'ADMINISTRACIÓN EN RR.HH' },
          { value: 'ADMINISTRACIÓN HOTELERA', label: 'ADMINISTRACIÓN HOTELERA' },
          { value: 'ADMINISTRADOR', label: 'ADMINISTRADOR' },
          { value: 'ADMINISTRADOR DE EMPRESAS', label: 'ADMINISTRADOR DE EMPRESAS' },
          { value: 'ADMINISTRADOR DE RECURSOS TURISTICOS', label: 'ADMINISTRADOR DE RECURSOS TURISTICOS' },
          { value: 'ADMINISTRADOR DE RED', label: 'ADMINISTRADOR DE RED' },
          { value: 'ADMINISTRADOR DE SISTEMAS', label: 'ADMINISTRADOR DE SISTEMAS' },
          { value: 'ADMINISTRADOR EN COMERCIO EXTERIOR', label: 'ADMINISTRADOR EN COMERCIO EXTERIOR' },
          { value: 'ADMINISTRADOR EN GASTRONOMIA', label: 'ADMINISTRADOR EN GASTRONOMIA' },
          { value: 'ADMINISTRADOR EN SEGURIDAD PUBLICA', label: 'ADMINISTRADOR EN SEGURIDAD PUBLICA' },
          { value: 'ADMINISTRADOR EN TURISMO Y/O HOTELERIA', label: 'ADMINISTRADOR EN TURISMO Y/O HOTELERIA' },
          { value: 'ADMINISTRADOR FINANCIERO', label: 'ADMINISTRADOR FINANCIERO' },
          { value: 'ADMINISTRADOR HOTELERO', label: 'ADMINISTRADOR HOTELERO' },
          { value: 'ADMINISTRADOR INDUSTRIAL', label: 'ADMINISTRADOR INDUSTRIAL' },
          { value: 'ADMINISTRADOR PUBLICO', label: 'ADMINISTRADOR PUBLICO' },
          { value: 'ADMINISTRADOR(A) COMERCIAL', label: 'ADMINISTRADOR(A) COMERCIAL' },
          { value: 'ADMINISTRADOR(A) DE EMPRESAS BILINGÜE', label: 'ADMINISTRADOR(A) DE EMPRESAS BILINGÜE' },
          { value: 'ADMINISTRADOR(A) DE RED', label: 'ADMINISTRADOR(A) DE RED' },
          { value: 'ADMINISTRADOR(A) INSTITUCIONAL', label: 'ADMINISTRADOR(A) INSTITUCIONAL' },
          { value: 'ADMINISTRADOR(A) PÚBLICO', label: 'ADMINISTRADOR(A) PÚBLICO' },
          { value: 'ADMINISTRADOR(A) RECURSOS HUMANOS', label: 'ADMINISTRADOR(A) RECURSOS HUMANOS' },
          { value: 'ADMINISTRATIVO', label: 'ADMINISTRATIVO' },
          { value: 'ADMINISTRATIVO BANCARIO', label: 'ADMINISTRATIVO BANCARIO' },
          { value: 'ADMINISTRATIVO BANCO ESTADO', label: 'ADMINISTRATIVO BANCO ESTADO' },
          { value: 'ADMINISTRATIVO CONTABLE', label: 'ADMINISTRATIVO CONTABLE' },
          { value: 'AERONÁUTICA', label: 'AERONÁUTICA' },
          { value: 'AGENTE COMERCIAL', label: 'AGENTE COMERCIAL' },
          { value: 'AGENTE CORPORATIVO', label: 'AGENTE CORPORATIVO' },
          { value: 'AGENTE DE OFICINA', label: 'AGENTE DE OFICINA' },
          { value: 'AGENTE DE VENTAS', label: 'AGENTE DE VENTAS' },
          { value: 'AGENTE DE VIAJE', label: 'AGENTE DE VIAJE' },
          { value: 'AGENTE RENTAS VITALICIAS', label: 'AGENTE RENTAS VITALICIAS' },
          { value: 'AGENDE DE SEGUROS', label: 'AGENDE DE SEGUROS' },
          { value: 'AGRICULTOR', label: 'AGRICULTOR' },
          { value: 'AGRICULTOR(A)', label: 'AGRICULTOR(A)' },
          { value: 'AGRÓNOMO', label: 'AGRÓNOMO' },
          { value: 'ALTO EJECUTIVO', label: 'ALTO EJECUTIVO' },
          { value: 'ANALISTA', label: 'ANALISTA' },
          { value: 'ANALISTA CONTABLE', label: 'ANALISTA CONTABLE' },
          { value: 'ANALISTA CTAS. CORRIENTES', label: 'ANALISTA CTAS. CORRIENTES' },
          { value: 'ANALISTA DE CRÉDITO', label: 'ANALISTA DE CRÉDITO' },
          { value: 'ANALISTA DE OPERACIÓN', label: 'ANALISTA DE OPERACIÓN' },
          { value: 'ANALISTA DE SISTEMA', label: 'ANALISTA DE SISTEMA' },
          { value: 'ANALISTA DE SISTEMAS', label: 'ANALISTA DE SISTEMAS' },
          { value: 'ANALISTA POLITICO', label: 'ANALISTA POLITICO' },
          { value: 'ANALISTA PROGRAMADOR', label: 'ANALISTA PROGRAMADOR' },
          { value: 'ANALISTA PROGRAMADORA', label: 'ANALISTA PROGRAMADORA' },
          { value: 'ANALISTA QUÍMICO', label: 'ANALISTA QUÍMICO' },
          { value: 'ANESTESIOLOGO', label: 'ANESTESIOLOGO' },
          { value: 'ANTROPÓLOGO(A)', label: 'ANTROPÓLOGO(A)' },
          { value: 'ARQUITECTO', label: 'ARQUITECTO' },
          { value: 'AROMA TERAPIA', label: 'AROMA TERAPIA' },
          { value: 'ARSENALERO', label: 'ARSENALERO' },
          { value: 'ARSENALERO(A)', label: 'ARSENALERO(A)' },
          { value: 'ARSENALERO(A) QUIRÚRGICA', label: 'ARSENALERO(A) QUIRÚRGICA' },
          { value: 'ARTESANO(A)', label: 'ARTESANO(A)' },
          { value: 'ARTESANO(A) EN MARMOLERÍA', label: 'ARTESANO(A) EN MARMOLERÍA' },
          { value: 'ASESOR', label: 'ASESOR' },
          { value: 'ASESOR EN COMERCIO EXTERIOR', label: 'ASESOR EN COMERCIO EXTERIOR' },
          { value: 'ASESOR POLITICO INTERNACIONAL', label: 'ASESOR POLITICO INTERNACIONAL' },
          { value: 'ASESOR(A) DE CRÉDITO HIPOTECARIO', label: 'ASESOR(A) DE CRÉDITO HIPOTECARIO' },
          { value: 'ASESOR(A) EDUCACIONAL', label: 'ASESOR(A) EDUCACIONAL' },
          { value: 'ASESOR(A) EN DIBUJO TÉCNICO', label: 'ASESOR(A) EN DIBUJO TÉCNICO' },
          { value: 'ASESOR(A) EN VENTAS', label: 'ASESOR(A) EN VENTAS' },
          { value: 'ASESOR(A) JURÍDICO', label: 'ASESOR(A) JURÍDICO' },
          { value: 'ASESORA DEL HOGAR', label: 'ASESORA DEL HOGAR' },
          { value: 'ASESORIA COSMETOLOGICA', label: 'ASESORIA COSMETOLOGICA' },
          { value: 'ASISTENTE ADMINISTRATIVO', label: 'ASISTENTE ADMINISTRATIVO' },
          { value: 'ASISTENTE COBRANZAS', label: 'ASISTENTE COBRANZAS' },
          { value: 'ASISTENTE COMERCIAL', label: 'ASISTENTE COMERCIAL' },
          { value: 'ASISTENTE CONTABLE', label: 'ASISTENTE CONTABLE' },
          { value: 'ASISTENTE DE CALIDAD', label: 'ASISTENTE DE CALIDAD' },
          { value: 'ASISTENTE DE CAPACITACION', label: 'ASISTENTE DE CAPACITACION' },
          { value: 'ASISTENTE DE EDUCACION', label: 'ASISTENTE DE EDUCACION' },
          { value: 'ASISTENTE DE ENFERMERÍA', label: 'ASISTENTE DE ENFERMERÍA' },
          { value: 'ASISTENTE DE GERENCIA', label: 'ASISTENTE DE GERENCIA' },
          { value: 'ASISTENTE DE PÁRVULOS', label: 'ASISTENTE DE PÁRVULOS' },
          { value: 'ASISTENTE DE REMUNERACIONES', label: 'ASISTENTE DE REMUNERACIONES' },
          { value: 'ASISTENTE DE SERVICIO', label: 'ASISTENTE DE SERVICIO' },
          { value: 'ASISTENTE DE VENTAS', label: 'ASISTENTE DE VENTAS' },
          { value: 'ASISTENTE DENTAL', label: 'ASISTENTE DENTAL' },
          { value: 'ASISTENTE JURÍDICO', label: 'ASISTENTE JURÍDICO' },
          { value: 'ASISTENTE LABORAL', label: 'ASISTENTE LABORAL' },
          { value: 'ASISTENTE LEGAL', label: 'ASISTENTE LEGAL' },
          { value: 'ASISTENTE PREVISIONAL', label: 'ASISTENTE PREVISIONAL' },
          { value: 'ASISTENTE RECURSOS HUMANOS', label: 'ASISTENTE RECURSOS HUMANOS' },
          { value: 'ASISTENTE SOCIAL', label: 'ASISTENTE SOCIAL' },
          { value: 'ASISTENTE TELEFÓNICO', label: 'ASISTENTE TELEFÓNICO' },
          { value: 'ASTRONÓNOMO(A)', label: 'ASTRONÓNOMO(A)' },
          { value: 'ASTRONOMO', label: 'ASTRONOMO' },
          { value: 'AUDITOR(A)', label: 'AUDITOR(A)' },
          { value: 'AUXILIAR DE ENFERMERÍA', label: 'AUXILIAR DE ENFERMERÍA' },
          { value: 'AUXILIAR DE FARMACIA', label: 'AUXILIAR DE FARMACIA' },
          { value: 'AUXILIAR DE PISO', label: 'AUXILIAR DE PISO' },
          { value: 'AUXILIAR DE VUELO', label: 'AUXILIAR DE VUELO' },
          { value: 'AUXILIAR PARAMÉDICO', label: 'AUXILIAR PARAMÉDICO' },
          { value: 'AUXILIAR TÉCNICO DE FARMACIA', label: 'AUXILIAR TÉCNICO DE FARMACIA' },
          { value: 'AUXILIAR Y ADMINISTRATIVO', label: 'AUXILIAR Y ADMINISTRATIVO' },
          { value: 'AYUDANTE CONTADOR', label: 'AYUDANTE CONTADOR' },
          { value: 'BACK OFFICE', label: 'BACK OFFICE' },
          { value: 'BAILARÍN(A) CLÁSICO', label: 'BAILARÍN(A) CLÁSICO' },
          { value: 'BANCARIO(A)', label: 'BANCARIO(A)' },
          { value: 'BIBLIOTECARIO', label: 'BIBLIOTECARIO' },
          { value: 'BIBLIOTECARIO(A)', label: 'BIBLIOTECARIO(A)' },
          { value: 'BIOINGENIERO', label: 'BIOINGENIERO' },
          { value: 'BIÓLOGO', label: 'BIÓLOGO' },
          { value: 'BIOQUÍMICA(A)', label: 'BIOQUÍMICA(A)' },
          { value: 'BIOQUIMICO', label: 'BIOQUIMICO' },
          { value: 'BIOTECNOLOGO', label: 'BIOTECNOLOGO' },
          { value: 'BIOTECNOLOGO DENTAL(A)', label: 'BIOTECNOLOGO DENTAL(A)' },
          { value: 'BODEGUERO(A)', label: 'BODEGUERO(A)' },
          { value: 'CAJERO ADMINISTRATIVO(A)', label: 'CAJERO ADMINISTRATIVO(A)' },
          { value: 'CAJERO BANCARIO(A)', label: 'CAJERO BANCARIO(A)' },
          { value: 'CAJERO VENDEDOR(A)', label: 'CAJERO VENDEDOR(A)' },
          { value: 'CAJERO(A)', label: 'CAJERO(A)' },
          { value: 'CAMARERO(A)', label: 'CAMARERO(A)' },
          { value: 'CARABINERO', label: 'CARABINERO' },
          { value: 'CARPINTERO', label: 'CARPINTERO' },
          { value: 'CARTERO', label: 'CARTERO' },
          { value: 'CARTOGRAFO', label: 'CARTOGRAFO' },
          { value: 'CHEF', label: 'CHEF' },
          { value: 'CHOFER', label: 'CHOFER' },
          { value: 'CHOFER PARTIME', label: 'CHOFER PARTIME' },
          { value: 'CIRUJANO DENTISTA', label: 'CIRUJANO DENTISTA' },
          { value: 'COMERCIANTE', label: 'COMERCIANTE' },
          { value: 'COMERCIANTE AGRICULTOR', label: 'COMERCIANTE AGRICULTOR' },
          { value: 'COMERCIANTE INDEPENDIENTE', label: 'COMERCIANTE INDEPENDIENTE' },
          { value: 'COMERCIO EXTERIOR', label: 'COMERCIO EXTERIOR' },
          { value: 'COMUNICADOR AUDIOVISUAL', label: 'COMUNICADOR AUDIOVISUAL' },
          { value: 'COMUNICADOR MULTIMEDIA', label: 'COMUNICADOR MULTIMEDIA' },
          { value: 'COMUNICADOR SOCIAL', label: 'COMUNICADOR SOCIAL' },
          { value: 'CONDUCTOR PROFESIONAL', label: 'CONDUCTOR PROFESIONAL' },
          { value: 'CONDUCTOR(A)', label: 'CONDUCTOR(A)' },
          { value: 'CONDUCTOR(A) BUSES', label: 'CONDUCTOR(A) BUSES' },
          { value: 'CONDUCTOR(A) DE TELEVISIÓN', label: 'CONDUCTOR(A) DE TELEVISIÓN' },
          { value: 'CONDUCTOR(A) EMPRESA SEGURIDAD', label: 'CONDUCTOR(A) EMPRESA SEGURIDAD' },
          { value: 'CONDUCTOR(A) METRO', label: 'CONDUCTOR(A) METRO' },
          { value: 'CONSEJERA DE CLIENTES', label: 'CONSEJERA DE CLIENTES' },
          { value: 'CONSULTOR', label: 'CONSULTOR' },
          { value: 'CONSULTOR(A)', label: 'CONSULTOR(A)' },
          { value: 'CONSULTOR(A) INFORMÁTICO', label: 'CONSULTOR(A) INFORMÁTICO' },
          { value: 'CONTABLE Y ESTUDIANTE', label: 'CONTABLE Y ESTUDIANTE' },
          { value: 'CONTADOR', label: 'CONTADOR' },
          { value: 'CONTADOR AUDITOR', label: 'CONTADOR AUDITOR' },
          { value: 'CONTADOR(A)', label: 'CONTADOR(A)' },
          { value: 'CONTADOR(A) GENERAL', label: 'CONTADOR(A) GENERAL' },
          { value: 'CONTADOR(A) PÚBLICO AUDITOR', label: 'CONTADOR(A) PÚBLICO AUDITOR' },
          { value: 'CONTRALOR', label: 'CONTRALOR' },
          { value: 'CONTRATISTA', label: 'CONTRATISTA' },
          { value: 'CONTROL DE CALIDAD', label: 'CONTROL DE CALIDAD' },
          { value: 'CONTROL INDUSTRIAL', label: 'CONTROL INDUSTRIAL' },
          { value: 'CONTROLADOR DE TRANSITO AEREO', label: 'CONTROLADOR DE TRANSITO AEREO' },
          { value: 'CONTROLADOR(A) DE TRANSITO AÉREO', label: 'CONTROLADOR(A) DE TRANSITO AÉREO' },
          { value: 'COORDINADOR', label: 'COORDINADOR' },
          { value: 'COORDINADOR(A)', label: 'COORDINADOR(A)' },
          { value: 'COORDINADOR(A) DE POST VENTA', label: 'COORDINADOR(A) DE POST VENTA' },
          { value: 'COORDINADOR(A) DE RRHH', label: 'COORDINADOR(A) DE RRHH' },
          { value: 'COORDINADOR(A) GENERAL', label: 'COORDINADOR(A) GENERAL' },
          { value: 'CORREDOR DE PROPIEDADES', label: 'CORREDOR DE PROPIEDADES' },
          { value: 'CORREDOR DE SEGUROS', label: 'CORREDOR DE SEGUROS' },
          { value: 'CORREDOR DE SEGUROS Y PROFESOR', label: 'CORREDOR DE SEGUROS Y PROFESOR' },
          { value: 'CORTADOR TEXTIL', label: 'CORTADOR TEXTIL' },
          { value: 'COSMETÓLOGO(A)', label: 'COSMETÓLOGO(A)' },
          { value: 'COSMETOLOGO', label: 'COSMETOLOGO' },
          { value: 'DECORADOR DE INTERIORES', label: 'DECORADOR DE INTERIORES' },
          { value: 'DECORADOR(A)', label: 'DECORADOR(A)' },
          { value: 'DECORADOR(A) DE INTERIOR', label: 'DECORADOR(A) DE INTERIOR' },
          { value: 'DENTISTA', label: 'DENTISTA' },
          { value: 'DEPORTISTA PROFESIONAL', label: 'DEPORTISTA PROFESIONAL' },
          { value: 'DESABOLLADOR', label: 'DESABOLLADOR' },
          { value: 'DESEMPLEADO - BUSCA TRABAJO', label: 'DESEMPLEADO - BUSCA TRABAJO' },
          { value: 'DESARROLLADOR INFORMATICO', label: 'DESARROLLADOR INFORMATICO' },
          { value: 'DETECTIVE', label: 'DETECTIVE' },
          { value: 'DIBUJANTE', label: 'DIBUJANTE' },
          { value: 'DIBUJANTE ARQUITECTÓNICO', label: 'DIBUJANTE ARQUITECTÓNICO' },
          { value: 'DIBUJANTE EN OBRAS CIVILES', label: 'DIBUJANTE EN OBRAS CIVILES' },
          { value: 'DIBUJANTE GRAFICO', label: 'DIBUJANTE GRAFICO' },
          { value: 'DIBUJANTE PORYECTISTA', label: 'DIBUJANTE PORYECTISTA' },
          { value: 'DIBUJANTE PROYECTISTA', label: 'DIBUJANTE PROYECTISTA' },
          { value: 'DIBUJANTE TÉCNICO', label: 'DIBUJANTE TÉCNICO' },
          { value: 'DIRECCIÓN Y PRODUCCIÓN DE TV', label: 'DIRECCIÓN Y PRODUCCIÓN DE TV' },
          { value: 'DISCAPACITADO(A)', label: 'DISCAPACITADO(A)' },
          { value: 'DISEÑADOR CON MENCIÓN EN COMUNIDAD', label: 'DISEÑADOR CON MENCIÓN EN COMUNIDAD' },
          { value: 'DISEÑADOR DE INTERIORES', label: 'DISEÑADOR DE INTERIORES' },
          { value: 'DISEÑADOR DE VESTUARIO', label: 'DISEÑADOR DE VESTUARIO' },
          { value: 'DISEÑADOR GRAFICO', label: 'DISEÑADOR GRAFICO' },
          { value: 'DISEÑADOR INDUSTRIAL', label: 'DISEÑADOR INDUSTRIAL' },
          { value: 'DISEÑADOR(A)', label: 'DISEÑADOR(A)' },
          { value: 'DISEÑADOR(A) ARSENALERO', label: 'DISEÑADOR(A) ARSENALERO' },
          { value: 'DISEÑADOR(A) DE AMBIENTE', label: 'DISEÑADOR(A) DE AMBIENTE' },
          { value: 'DISEÑADOR(A) DE VESTUARIO', label: 'DISEÑADOR(A) DE VESTUARIO' },
          { value: 'DISEÑADOR(A) GRÁFICO', label: 'DISEÑADOR(A) GRÁFICO' },
          { value: 'DISEÑADOR(A) INDUSTRIAL', label: 'DISEÑADOR(A) INDUSTRIAL' },
          { value: 'DISEÑADOR(A) TEXTIL', label: 'DISEÑADOR(A) TEXTIL' },
          { value: 'DOCTOR EN MATEMATICAS', label: 'DOCTOR EN MATEMATICAS' },
          { value: 'DOCTOR EN QUIMICA', label: 'DOCTOR EN QUIMICA' },
          { value: 'DOCTOR(A) EN FÍSICA', label: 'DOCTOR(A) EN FÍSICA' },
          { value: 'DUEÑA DE CASA', label: 'DUEÑA DE CASA' },
          { value: 'ECONOMISTA', label: 'ECONOMISTA' },
          { value: 'ED. DE PARVULOS', label: 'ED. DE PARVULOS' },
          { value: 'EDUCADORA DE PÁRVULOS', label: 'EDUCADORA DE PÁRVULOS' },
          { value: 'EDUCADORA DIFERENCIAL', label: 'EDUCADORA DIFERENCIAL' },
          { value: 'EGRESADO(A) COMERC. EXTERIOR', label: 'EGRESADO(A) COMERC. EXTERIOR' },
          { value: 'EGRESADO(A) DE DERECHO', label: 'EGRESADO(A) DE DERECHO' },
          { value: 'EJECUTIVO COMERCIAL', label: 'EJECUTIVO COMERCIAL' },
          { value: 'EJECUTIVO DE ATENCION CLIENTES', label: 'EJECUTIVO DE ATENCION CLIENTES' },
          { value: 'EJECUTIVO DE BANCO', label: 'EJECUTIVO DE BANCO' },
          { value: 'EJECUTIVO DE CUENTAS', label: 'EJECUTIVO DE CUENTAS' },
          { value: 'EJECUTIVO DE INVERSIONES', label: 'EJECUTIVO DE INVERSIONES' },
          { value: 'EJECUTIVO DE VENTAS', label: 'EJECUTIVO DE VENTAS' },
          { value: 'EJECUTIVO MEDIO / PROFESIONAL', label: 'EJECUTIVO MEDIO / PROFESIONAL' },
          { value: 'EJECUTIVO(A)', label: 'EJECUTIVO(A)' },
          { value: 'EJECUTIVO(A) ADMINISTRATIVO', label: 'EJECUTIVO(A) ADMINISTRATIVO' },
          { value: 'EJECUTIVO(A) ATENCIÓN CLIENTE', label: 'EJECUTIVO(A) ATENCIÓN CLIENTE' },
          { value: 'EJECUTIVO(A) CAE', label: 'EJECUTIVO(A) CAE' },
          { value: 'EJECUTIVO(A) CALL CENTER', label: 'EJECUTIVO(A) CALL CENTER' },
          { value: 'EJECUTIVO(A) COMERCIAL', label: 'EJECUTIVO(A) COMERCIAL' },
          { value: 'EJECUTIVO(A) COMPAÑÍA SEGUROS', label: 'EJECUTIVO(A) COMPAÑÍA SEGUROS' },
          { value: 'EJECUTIVO(A) CRED Y COBRAN ADMIN', label: 'EJECUTIVO(A) CRED Y COBRAN ADMIN' },
          { value: 'EJECUTIVO(A) DE BANCO', label: 'EJECUTIVO(A) DE BANCO' },
          { value: 'EJECUTIVO(A) DE CLIENTES', label: 'EJECUTIVO(A) DE CLIENTES' },
          { value: 'EJECUTIVO(A) DE COBRANZA', label: 'EJECUTIVO(A) DE COBRANZA' },
          { value: 'EJECUTIVO(A) DE CUENTAS', label: 'EJECUTIVO(A) DE CUENTAS' },
          { value: 'EJECUTIVO(A) DE INVERSIONES', label: 'EJECUTIVO(A) DE INVERSIONES' },
          { value: 'EJECUTIVO(A) DE NEGOCIOS', label: 'EJECUTIVO(A) DE NEGOCIOS' },
          { value: 'EJECUTIVO(A) DE SEGURO', label: 'EJECUTIVO(A) DE SEGURO' },
          { value: 'EJECUTIVO(A) DE TELEMARKETING', label: 'EJECUTIVO(A) DE TELEMARKETING' },
          { value: 'EJECUTIVO(A) DE VENTAS', label: 'EJECUTIVO(A) DE VENTAS' },
          { value: 'EJECUTIVO(A) INMOBILIARIO', label: 'EJECUTIVO(A) INMOBILIARIO' },
          { value: 'EJECUTIVO(A) SERVICIO AL CLIENTE', label: 'EJECUTIVO(A) SERVICIO AL CLIENTE' },
          { value: 'EJECUTIVO(A) TELEMARKETING', label: 'EJECUTIVO(A) TELEMARKETING' },
          { value: 'ELÉCTRICO MECÁNICO', label: 'ELÉCTRICO MECÁNICO' },
          { value: 'ELECTRICISTA', label: 'ELECTRICISTA' },
          { value: 'ELECTRÓNICO', label: 'ELECTRÓNICO' },
          { value: 'ELECTROMECANICO', label: 'ELECTROMECANICO' },
          { value: 'EMFERMERO(A)', label: 'EMFERMERO(A)' },
          { value: 'EMPLEADO ADMINISTRATIVO', label: 'EMPLEADO ADMINISTRATIVO' },
          { value: 'EMPLEADO FUERZAS ARMADAS', label: 'EMPLEADO FUERZAS ARMADAS' },
          { value: 'EMPLEADO(A)', label: 'EMPLEADO(A)' },
          { value: 'EMPLEADO(A) ADMINISTRATIVO', label: 'EMPLEADO(A) ADMINISTRATIVO' },
          { value: 'EMPLEADO(A) BANCARIO', label: 'EMPLEADO(A) BANCARIO' },
          { value: 'EMPLEADO(A) FISCAL', label: 'EMPLEADO(A) FISCAL' },
          { value: 'EMPLEADO(A) PARTICULAR', label: 'EMPLEADO(A) PARTICULAR' },
          { value: 'EMPLEADO(A) PÚBLICO', label: 'EMPLEADO(A) PÚBLICO' },
          { value: 'EMPRESARIO', label: 'EMPRESARIO' },
          { value: 'EMPRESARIO / COMERCIANTE / INDEPENDIENTE', label: 'EMPRESARIO / COMERCIANTE / INDEPENDIENTE' },
          { value: 'EMPRESARIO Y SOCIO', label: 'EMPRESARIO Y SOCIO' },
          { value: 'ENCARGADO DE MAQUINARIA', label: 'ENCARGADO DE MAQUINARIA' },
          { value: 'ENFERMERA', label: 'ENFERMERA' },
          { value: 'ENFERMERO', label: 'ENFERMERO' },
          { value: 'ENFERMERO(A) UNIVERSITARIO(A)', label: 'ENFERMERO(A) UNIVERSITARIO(A)' },
          { value: 'ENTRENADOR DEPORTIVO', label: 'ENTRENADOR DEPORTIVO' },
          { value: 'ESPECIALISTA EN CRIOGENIA Y VACIO', label: 'ESPECIALISTA EN CRIOGENIA Y VACIO' },
          { value: 'ESPECIALISTA EN IDIOMAS', label: 'ESPECIALISTA EN IDIOMAS' },
          { value: 'ESPECIALISTA EN PERSONAL', label: 'ESPECIALISTA EN PERSONAL' },
          { value: 'ESPECIALISTA EN SEGURIDAD AEROPORTUARIA', label: 'ESPECIALISTA EN SEGURIDAD AEROPORTUARIA' },
          { value: 'ESCRITOR(A)', label: 'ESCRITOR(A)' },
          { value: 'ESTETICISTA', label: 'ESTETICISTA' },
          { value: 'ESTILISTA', label: 'ESTILISTA' },
          { value: 'ESTILISTA PROFESIONAL', label: 'ESTILISTA PROFESIONAL' },
          { value: 'ESTUDIANTE', label: 'ESTUDIANTE' },
          { value: 'ESTUDIANTE - EGRESADO', label: 'ESTUDIANTE - EGRESADO' },
          { value: 'ESTUDIANTE DE INGENIERÍA', label: 'ESTUDIANTE DE INGENIERÍA' },
          { value: 'ESTUDIANTE DE MEDICINA', label: 'ESTUDIANTE DE MEDICINA' },
          { value: 'ESTUDIANTE DE PSICOLOGÍA', label: 'ESTUDIANTE DE PSICOLOGÍA' },
          { value: 'ESTUDIANTE QUÍMICA FARMACIA', label: 'ESTUDIANTE QUÍMICA FARMACIA' },
          { value: 'EXPERTO EN MANTENCIÓN DE EQUIPOS', label: 'EXPERTO EN MANTENCIÓN DE EQUIPOS' },
          { value: 'FABRICANTE', label: 'FABRICANTE' },
          { value: 'FISCALIZADOR', label: 'FISCALIZADOR' },
          { value: 'FISIOTERAPEUTA', label: 'FISIOTERAPEUTA' },
          { value: 'FONOAUDIOLAGO(A)', label: 'FONOAUDIOLAGO(A)' },
          { value: 'FONOAUDIOLOGO', label: 'FONOAUDIOLOGO' },
          { value: 'FOTÓGRAFO', label: 'FOTÓGRAFO' },
          { value: 'FRUTICULTOR', label: 'FRUTICULTOR' },
          { value: 'FUERZAS ARMADAS', label: 'FUERZAS ARMADAS' },
          { value: 'FUERZA AEREA', label: 'FUERZA AEREA' },
          { value: 'FUNCIONARIO INTERNACIONAL', label: 'FUNCIONARIO INTERNACIONAL' },
          { value: 'FUNCIONARIO PUBLICO', label: 'FUNCIONARIO PUBLICO' },
          { value: 'FUNCIONARIO(A) BANCO ESTADO', label: 'FUNCIONARIO(A) BANCO ESTADO' },
          { value: 'FUNCIONARIO(A) JUDICIAL', label: 'FUNCIONARIO(A) JUDICIAL' },
          { value: 'FUNCIONARIO(A) PUBLICO', label: 'FUNCIONARIO(A) PUBLICO' },
          { value: 'FUTBOLISTA PROFESIIONAL', label: 'FUTBOLISTA PROFESIIONAL' },
          { value: 'GARZÓN(A)', label: 'GARZÓN(A)' },
          { value: 'GASFITER', label: 'GASFITER' },
          { value: 'GASTRONOMÍA', label: 'GASTRONOMÍA' },
          { value: 'GENDARME', label: 'GENDARME' },
          { value: 'GENERAL DE CARABINERO EN RETIRO', label: 'GENERAL DE CARABINERO EN RETIRO' },
          { value: 'GEOFISICO', label: 'GEOFISICO' },
          { value: 'GEÓGRAFO', label: 'GEÓGRAFO' },
          { value: 'GEÓLOGO', label: 'GEÓLOGO' },
          { value: 'GERENTE', label: 'GERENTE' },
          { value: 'GERENTE SEGURIDAD Y MEDIO AMB.', label: 'GERENTE SEGURIDAD Y MEDIO AMB.' },
          { value: 'GERENTE ZONAL', label: 'GERENTE ZONAL' },
          { value: 'GERENTE(A) DE FINANZAS', label: 'GERENTE(A) DE FINANZAS' },
          { value: 'GESTOR CULTURAL', label: 'GESTOR CULTURAL' },
          { value: 'GUARDIA', label: 'GUARDIA' },
          { value: 'GUARDIA DE SEGURIDAD', label: 'GUARDIA DE SEGURIDAD' },
          { value: 'HOTELERO(A)', label: 'HOTELERO(A)' },
          { value: 'ILUSTRADOR', label: 'ILUSTRADOR' },
          { value: 'IMPORTACIÓN Y EXPORTACIÓN', label: 'IMPORTACIÓN Y EXPORTACIÓN' },
          { value: 'IMPRESOR GRAFICO', label: 'IMPRESOR GRAFICO' },
          { value: 'INDEPENDIENTE', label: 'INDEPENDIENTE' },
          { value: 'INDUSTRIAL', label: 'INDUSTRIAL' },
          { value: 'INETERPRETE INGLÉS CASTELLANO', label: 'INETERPRETE INGLÉS CASTELLANO' },
          { value: 'INFORMÁTICO(A)', label: 'INFORMÁTICO(A)' },
          { value: 'INFORMATICO', label: 'INFORMATICO' },
          { value: 'ING. AGROINDUSTRIAL', label: 'ING. AGROINDUSTRIAL' },
          { value: 'ING. AGRONOMO', label: 'ING. AGRONOMO' },
          { value: 'ING. AMBIENTAL', label: 'ING. AMBIENTAL' },
          { value: 'ING. BIOMEDICO', label: 'ING. BIOMEDICO' },
          { value: 'ING. CIVIL', label: 'ING. CIVIL' },
          { value: 'ING. CIVIL AMBIENTAL', label: 'ING. CIVIL AMBIENTAL' },
          { value: 'ING. CIVIL BIOMEDICO', label: 'ING. CIVIL BIOMEDICO' },
          { value: 'ING. CIVIL ELECTRICO', label: 'ING. CIVIL ELECTRICO' },
          { value: 'ING. CIVIL EN CONSTRUCCION', label: 'ING. CIVIL EN CONSTRUCCION' },
          { value: 'ING. CIVIL EN ELECTRICIDAD', label: 'ING. CIVIL EN ELECTRICIDAD' },
          { value: 'ING. CIVIL EN ELECTRONICA', label: 'ING. CIVIL EN ELECTRONICA' },
          { value: 'ING. CIVIL EN ESTRUCTURAS', label: 'ING. CIVIL EN ESTRUCTURAS' },
          { value: 'ING. CIVIL EN INFORMATICA', label: 'ING. CIVIL EN INFORMATICA' },
          { value: 'ING. CIVIL EN MATEMATICAS', label: 'ING. CIVIL EN MATEMATICAS' },
          { value: 'ING. CIVIL EN MATERIALES', label: 'ING. CIVIL EN MATERIALES' },
          { value: 'ING. CIVIL EN MECANICA', label: 'ING. CIVIL EN MECANICA' },
          { value: 'ING. CIVIL EN MECATRONICA', label: 'ING. CIVIL EN MECATRONICA' },
          { value: 'ING. CIVIL EN MEDIOAMBIENTE', label: 'ING. CIVIL EN MEDIOAMBIENTE' },
          { value: 'ING. CIVIL EN METALURGIA', label: 'ING. CIVIL EN METALURGIA' },
          { value: 'ING. CIVIL EN MINERIA', label: 'ING. CIVIL EN MINERIA' },
          { value: 'ING. CIVIL EN OBRAS CIVILES', label: 'ING. CIVIL EN OBRAS CIVILES' },
          { value: 'ING. CIVIL EN QUIMICA', label: 'ING. CIVIL EN QUIMICA' },
          { value: 'ING. CIVIL EN TELECOMUNICACIONES', label: 'ING. CIVIL EN TELECOMUNICACIONES' },
          { value: 'ING. CIVIL EN TRANSPORTE', label: 'ING. CIVIL EN TRANSPORTE' },
          { value: 'ING. CIVIL HIDRAULICO', label: 'ING. CIVIL HIDRAULICO' },
          { value: 'ING. CIVIL INDUSTRIAL', label: 'ING. CIVIL INDUSTRIAL' },
          { value: 'ING. COMERCIAL', label: 'ING. COMERCIAL' },
          { value: 'ING. DE EJECUCION', label: 'ING. DE EJECUCION' },
          { value: 'ING. DE EJECUCION AMBIENTAL', label: 'ING. DE EJECUCION AMBIENTAL' },
          { value: 'ING. DE EJECUCION EN ADMINISTRACION', label: 'ING. DE EJECUCION EN ADMINISTRACION' },
          { value: 'ING. DE EJECUCION EN AGRONOMIA', label: 'ING. DE EJECUCION EN AGRONOMIA' },
          { value: 'ING. DE EJECUCION EN CLIMATIZACION', label: 'ING. DE EJECUCION EN CLIMATIZACION' },
          { value: 'ING. DE EJECUCION EN COMERCIO EXTERIOR', label: 'ING. DE EJECUCION EN COMERCIO EXTERIOR' },
          { value: 'ING. DE EJECUCION EN ELECTRICIDAD', label: 'ING. DE EJECUCION EN ELECTRICIDAD' },
          { value: 'ING. DE EJECUCION EN GEOMESURA', label: 'ING. DE EJECUCION EN GEOMESURA' },
          { value: 'ING. DE EJECUCION EN GESTION INDUSTRIAL', label: 'ING. DE EJECUCION EN GESTION INDUSTRIAL' },
          { value: 'ING. DE EJECUCION EN INFORMATICA', label: 'ING. DE EJECUCION EN INFORMATICA' },
          { value: 'ING. DE EJECUCION EN MARKETING', label: 'ING. DE EJECUCION EN MARKETING' },
          { value: 'ING. DE EJECUCION EN MECANICA', label: 'ING. DE EJECUCION EN MECANICA' },
          { value: 'ING. DE EJECUCION EN PREVENCION DE RIESGOS', label: 'ING. DE EJECUCION EN PREVENCION DE RIESGOS' },
          { value: 'ING. DE EJECUCION EN QUIMICA', label: 'ING. DE EJECUCION EN QUIMICA' },
          { value: 'ING. DE EJECUCION EN SISTEMAS AERONAUTICOS', label: 'ING. DE EJECUCION EN SISTEMAS AERONAUTICOS' },
          { value: 'ING. DE EJECUCION INDUSTRIAL', label: 'ING. DE EJECUCION INDUSTRIAL' },
          { value: 'ING. EJECUCCION EN MINERIA', label: 'ING. EJECUCCION EN MINERIA' },
          { value: 'ING. EJECUCIÓN', label: 'ING. EJECUCIÓN' },
          { value: 'ING. ELECTRICO', label: 'ING. ELECTRICO' },
          { value: 'ING. EN ADMINISTRACION AGROINDUSTRIAL', label: 'ING. EN ADMINISTRACION AGROINDUSTRIAL' },
          { value: 'ING. EN ADMINISTRACION DE EMPRESAS', label: 'ING. EN ADMINISTRACION DE EMPRESAS' },
          { value: 'ING. EN ADMINISTRACION DE RECURSOS HUMANOS', label: 'ING. EN ADMINISTRACION DE RECURSOS HUMANOS' },
          { value: 'ING. EN ADMINISTRACION HOTELERA', label: 'ING. EN ADMINISTRACION HOTELERA' },
          { value: 'ING. EN ADMINISTRACION PUBLICA', label: 'ING. EN ADMINISTRACION PUBLICA' },
          { value: 'ING. EN ADMINISTRACION TURISTICA', label: 'ING. EN ADMINISTRACION TURISTICA' },
          { value: 'ING. EN AERONAUTICA', label: 'ING. EN AERONAUTICA' },
          { value: 'ING. EN AGRIMENSURA', label: 'ING. EN AGRIMENSURA' },
          { value: 'ING. EN AGRONEGOCIOS', label: 'ING. EN AGRONEGOCIOS' },
          { value: 'ING. EN AGRONOMIA', label: 'ING. EN AGRONOMIA' },
          { value: 'ING. EN ALIMENTOS', label: 'ING. EN ALIMENTOS' },
          { value: 'ING. EN AUTOMATIZACION', label: 'ING. EN AUTOMATIZACION' },
          { value: 'ING. EN AUTOMATIZACION INDUSTRIAL', label: 'ING. EN AUTOMATIZACION INDUSTRIAL' },
          { value: 'ING. EN BIOTECNOLOGIA', label: 'ING. EN BIOTECNOLOGIA' },
          { value: 'ING. EN CIENCIAS FORENSES', label: 'ING. EN CIENCIAS FORENSES' },
          { value: 'ING. EN CLIMATIZACION', label: 'ING. EN CLIMATIZACION' },
          { value: 'ING. EN COMERCIO EXTERIOR', label: 'ING. EN COMERCIO EXTERIOR' },
          { value: 'ING. EN COMUNICACIONES', label: 'ING. EN COMUNICACIONES' },
          { value: 'ING. EN CONECTIVIDAD Y REDES', label: 'ING. EN CONECTIVIDAD Y REDES' },
          { value: 'ING. EN CONSTRUCCION', label: 'ING. EN CONSTRUCCION' },
          { value: 'ING. EN CONTROL DE GESTION', label: 'ING. EN CONTROL DE GESTION' },
          { value: 'ING. EN CONTRUCCION', label: 'ING. EN CONTRUCCION' },
          { value: 'ING. EN EJECUCION INDUSTRIAL', label: 'ING. EN EJECUCION INDUSTRIAL' },
          { value: 'ING. EN ELECTRICIDAD', label: 'ING. EN ELECTRICIDAD' },
          { value: 'ING. EN ELECTRICIDAD Y AUTOMATIZACION', label: 'ING. EN ELECTRICIDAD Y AUTOMATIZACION' },
          { value: 'ING. EN ELECTRONICA', label: 'ING. EN ELECTRONICA' },
          { value: 'ING. EN ESTADISTICA', label: 'ING. EN ESTADISTICA' },
          { value: 'ING. EN FINANZAS', label: 'ING. EN FINANZAS' },
          { value: 'ING. EN FINZANZAS', label: 'ING. EN FINZANZAS' },
          { value: 'ING. EN FISICA', label: 'ING. EN FISICA' },
          { value: 'ING. EN GEOLOGIA', label: 'ING. EN GEOLOGIA' },
          { value: 'ING. EN GEOMENSURA', label: 'ING. EN GEOMENSURA' },
          { value: 'ING. EN GEOTECNICA', label: 'ING. EN GEOTECNICA' },
          { value: 'ING. EN GESTION COMERCIAL', label: 'ING. EN GESTION COMERCIAL' },
          { value: 'ING. EN GESTION DE LA CALIDAD', label: 'ING. EN GESTION DE LA CALIDAD' },
          { value: 'ING. EN GESTION DE RECURSOS', label: 'ING. EN GESTION DE RECURSOS' },
          { value: 'ING. EN GESTION DE RECURSOS HUMANOS', label: 'ING. EN GESTION DE RECURSOS HUMANOS' },
          { value: 'ING. EN GESTION E INFORMATICA', label: 'ING. EN GESTION E INFORMATICA' },
          { value: 'ING. EN GESTION OPERACIONAL', label: 'ING. EN GESTION OPERACIONAL' },
          { value: 'ING. EN INFORMACION U CONTROL DE GESTION', label: 'ING. EN INFORMACION U CONTROL DE GESTION' },
          { value: 'ING. EN INFORMACION Y CONTROL DE GESTION', label: 'ING. EN INFORMACION Y CONTROL DE GESTION' },
          { value: 'ING. EN INFORMATICA', label: 'ING. EN INFORMATICA' },
          { value: 'ING. EN INFRAESTRUCTURA', label: 'ING. EN INFRAESTRUCTURA' },
          { value: 'ING. EN LOGISTICA', label: 'ING. EN LOGISTICA' },
          { value: 'ING. EN MARKETING', label: 'ING. EN MARKETING' },
          { value: 'ING. EN MATEMATICAS', label: 'ING. EN MATEMATICAS' },
          { value: 'ING. EN MATERIALES', label: 'ING. EN MATERIALES' },
          { value: 'ING. EN MECANICA', label: 'ING. EN MECANICA' },
          { value: 'ING. EN MECANICA AUTOMOTRIZ', label: 'ING. EN MECANICA AUTOMOTRIZ' },
          { value: 'ING. EN MECATRONICA', label: 'ING. EN MECATRONICA' },
          { value: 'ING. EN MEDIO AMBIENTE', label: 'ING. EN MEDIO AMBIENTE' },
          { value: 'ING. EN METAL MECANICA', label: 'ING. EN METAL MECANICA' },
          { value: 'ING. EN METALURGIA', label: 'ING. EN METALURGIA' },
          { value: 'ING. EN MINERIA', label: 'ING. EN MINERIA' },
          { value: 'ING. EN NEGOCIOS', label: 'ING. EN NEGOCIOS' },
          { value: 'ING. EN NEGOCIOS INTERNACIONALES', label: 'ING. EN NEGOCIOS INTERNACIONALES' },
          { value: 'ING. EN PETROLEO', label: 'ING. EN PETROLEO' },
          { value: 'ING. EN PREVENCION DE RIESGOS', label: 'ING. EN PREVENCION DE RIESGOS' },
          { value: 'ING. EN PROYECTOS', label: 'ING. EN PROYECTOS' },
          { value: 'ING. EN QUIMICA', label: 'ING. EN QUIMICA' },
          { value: 'ING. EN QUIMICA INDUSTRIAL', label: 'ING. EN QUIMICA INDUSTRIAL' },
          { value: 'ING. EN RECURSOS HUMANOS', label: 'ING. EN RECURSOS HUMANOS' },
          { value: 'ING. EN RECURSOS NATURALES', label: 'ING. EN RECURSOS NATURALES' },
          { value: 'ING. EN REDES', label: 'ING. EN REDES' },
          { value: 'ING. EN SEGURIDAD INFORMATICA', label: 'ING. EN SEGURIDAD INFORMATICA' },
          { value: 'ING. EN SISTEMAS', label: 'ING. EN SISTEMAS' },
          { value: 'ING. EN SISTEMAS DE ARMAS', label: 'ING. EN SISTEMAS DE ARMAS' },
          { value: 'ING. EN SISTEMAS DE CALIDAD Y GESTION', label: 'ING. EN SISTEMAS DE CALIDAD Y GESTION' },
          { value: 'ING. EN SOFTWARE', label: 'ING. EN SOFTWARE' },
          { value: 'ING. EN TELECOMUNICACIONES', label: 'ING. EN TELECOMUNICACIONES' },
          { value: 'ING. EN TRANSPORTE', label: 'ING. EN TRANSPORTE' },
          { value: 'ING. EN TURISMO Y/O HOTELERIA', label: 'ING. EN TURISMO Y/O HOTELERIA' },
          { value: 'ING. FORESTAL', label: 'ING. FORESTAL' },
          { value: 'ING. INDUSTRIAL', label: 'ING. INDUSTRIAL' },
          { value: 'ING. PETRO QUIMICO', label: 'ING. PETRO QUIMICO' },
          { value: 'INGENERO EN TELECOMUNICACIONES', label: 'INGENERO EN TELECOMUNICACIONES' },
          { value: 'INGENIERO', label: 'INGENIERO' },
          { value: 'INGENIERO AGRÍCOLA', label: 'INGENIERO AGRÍCOLA' },
          { value: 'INGENIERO(A)', label: 'INGENIERO(A)' },
          { value: 'INGENIERO(A) ACUICULTOR', label: 'INGENIERO(A) ACUICULTOR' },
          { value: 'INGENIERO(A) AERONÁUTICO', label: 'INGENIERO(A) AERONÁUTICO' },
          { value: 'INGENIERO(A) AGRÓNOMO', label: 'INGENIERO(A) AGRÓNOMO' },
          { value: 'INGENIERO(A) AMBIENTAL', label: 'INGENIERO(A) AMBIENTAL' },
          { value: 'INGENIERO(A) AUTOMATIZACIÓN', label: 'INGENIERO(A) AUTOMATIZACIÓN' },
          { value: 'INGENIERO(A) CIVIL', label: 'INGENIERO(A) CIVIL' },
          { value: 'INGENIERO(A) CIVIL ELÉCTRICO', label: 'INGENIERO(A) CIVIL ELÉCTRICO' },
          { value: 'INGENIERO(A) CIVIL EN COMPUTACIÓN', label: 'INGENIERO(A) CIVIL EN COMPUTACIÓN' },
          { value: 'INGENIERO(A) CIVIL EN MINAS', label: 'INGENIERO(A) CIVIL EN MINAS' },
          { value: 'INGENIERO(A) CIVIL INDUSTRIAL', label: 'INGENIERO(A) CIVIL INDUSTRIAL' },
          { value: 'INGENIERO(A) CIVIL INFORMÁTICA', label: 'INGENIERO(A) CIVIL INFORMÁTICA' },
          { value: 'INGENIERO(A) CIVIL MECÁNICO', label: 'INGENIERO(A) CIVIL MECÁNICO' },
          { value: 'INGENIERO(A) CIVIL MECÁNICO Y METALMECÁNICA', label: 'INGENIERO(A) CIVIL MECÁNICO Y METALMECÁNICA' },
          { value: 'INGENIERO(A) CIVIL MINAS', label: 'INGENIERO(A) CIVIL MINAS' },
          { value: 'INGENIERO(A) CIVIL OBRAS CIVILES', label: 'INGENIERO(A) CIVIL OBRAS CIVILES' },
          { value: 'INGENIERO(A) CIVIL QUÍMICO', label: 'INGENIERO(A) CIVIL QUÍMICO' },
          { value: 'INGENIERO(A) CONTRUCCIÓN', label: 'INGENIERO(A) CONTRUCCIÓN' },
          { value: 'INGENIERO(A) EJE ADM PÚBLICA', label: 'INGENIERO(A) EJE ADM PÚBLICA' },
          { value: 'INGENIERO(A) EJECUCIÓN ADMINISTRACIÓN EMPRESAS', label: 'INGENIERO(A) EJECUCIÓN ADMINISTRACIÓN EMPRESAS' },
          { value: 'INGENIERO(A) EJECUCIÓN INDUSTRIAL', label: 'INGENIERO(A) EJECUCIÓN INDUSTRIAL' },
          { value: 'INGENIERO(A) EJECUCION INFORMÁTICA', label: 'INGENIERO(A) EJECUCION INFORMÁTICA' },
          { value: 'INGENIERO(A) EJECUCION MECÁNICA', label: 'INGENIERO(A) EJECUCION MECÁNICA' },
          { value: 'INGENIERO(A) ELÉCTRICO (A)', label: 'INGENIERO(A) ELÉCTRICO (A)' },
          { value: 'INGENIERO(A) ELECTROMECÁNICO', label: 'INGENIERO(A) ELECTROMECÁNICO' },
          { value: 'INGENIERO(A) EN ADMINISTRACIÓN', label: 'INGENIERO(A) EN ADMINISTRACIÓN' },
          { value: 'INGENIERO(A) EN ALIMENTOS', label: 'INGENIERO(A) EN ALIMENTOS' },
          { value: 'INGENIERO(A) EN COMERCIO', label: 'INGENIERO(A) EN COMERCIO' },
          { value: 'INGENIERO(A) EN COMERCIO EXTERIOR', label: 'INGENIERO(A) EN COMERCIO EXTERIOR' },
          { value: 'INGENIERO(A) EN COMERCIO INTERIOR', label: 'INGENIERO(A) EN COMERCIO INTERIOR' },
          { value: 'INGENIERO(A) EN COMPUTACIÓN', label: 'INGENIERO(A) EN COMPUTACIÓN' },
          { value: 'INGENIERO(A) EN CONSTRUCCIÓN', label: 'INGENIERO(A) EN CONSTRUCCIÓN' },
          { value: 'INGENIERO(A) EN EJEC.EN PREV.DE RIESGO', label: 'INGENIERO(A) EN EJEC.EN PREV.DE RIESGO' },
          { value: 'INGENIERO(A) EN EJECUCIÓN INFORMÁTICA', label: 'INGENIERO(A) EN EJECUCIÓN INFORMÁTICA' },
          { value: 'INGENIERO(A) EN EJECUCIÓN TEXTIL', label: 'INGENIERO(A) EN EJECUCIÓN TEXTIL' },
          { value: 'INGENIERO(A) EN ELECTRÓNICA', label: 'INGENIERO(A) EN ELECTRÓNICA' },
          { value: 'INGENIERO(A) EN GESTIÓN INFORMÁTICA', label: 'INGENIERO(A) EN GESTIÓN INFORMÁTICA' },
          { value: 'INGENIERO(A) EN INDUSTRIA ALIMENTOS', label: 'INGENIERO(A) EN INDUSTRIA ALIMENTOS' },
          { value: 'INGENIERO(A) EN INFORMÁTICA', label: 'INGENIERO(A) EN INFORMÁTICA' },
          { value: 'INGENIERO(A) EN MARKETING', label: 'INGENIERO(A) EN MARKETING' },
          { value: 'INGENIERO(A) EN MINAS', label: 'INGENIERO(A) EN MINAS' },
          { value: 'INGENIERO(A) EN PREVENCIÓN', label: 'INGENIERO(A) EN PREVENCIÓN' },
          { value: 'INGENIERO(A) EN RECURSOS HUMANOS', label: 'INGENIERO(A) EN RECURSOS HUMANOS' },
          { value: 'INGENIERO(A) EN RR. HH.', label: 'INGENIERO(A) EN RR. HH.' },
          { value: 'INGENIERO(A) EN SISTEMAS', label: 'INGENIERO(A) EN SISTEMAS' },
          { value: 'INGENIERO(A) EN SONIDO', label: 'INGENIERO(A) EN SONIDO' },
          { value: 'INGENIERO(A) EN TELECOMUNICACIONES', label: 'INGENIERO(A) EN TELECOMUNICACIONES' },
          { value: 'INGENIERO(A) EN TURISMO', label: 'INGENIERO(A) EN TURISMO' },
          { value: 'INGENIERO(A) ESTADÍSTICO', label: 'INGENIERO(A) ESTADÍSTICO' },
          { value: 'INGENIERO(A) FINANZAS', label: 'INGENIERO(A) FINANZAS' },
          { value: 'INGENIERO(A) FÍSICO', label: 'INGENIERO(A) FÍSICO' },
          { value: 'INGENIERO(A) FORESTAL', label: 'INGENIERO(A) FORESTAL' },
          { value: 'INGENIERO(A) INDUSTRIAL', label: 'INGENIERO(A) INDUSTRIAL' },
          { value: 'INGENIERO(A) INFORMACIÓN Y CONTROL DE GESTIÓN', label: 'INGENIERO(A) INFORMACIÓN Y CONTROL DE GESTIÓN' },
          { value: 'INGENIERO(A) MECÁNICO', label: 'INGENIERO(A) MECÁNICO' },
          { value: 'INGENIERO(A) MECÁNICO INDUSTRIAL', label: 'INGENIERO(A) MECÁNICO INDUSTRIAL' },
          { value: 'INGENIERO(A) MEDIO AMBIENTE', label: 'INGENIERO(A) MEDIO AMBIENTE' },
          { value: 'INGENIERO(A) PREVENCIÓN DE RIESGO', label: 'INGENIERO(A) PREVENCIÓN DE RIESGO' },
          { value: 'INGENIERO(A) QUÍMICO', label: 'INGENIERO(A) QUÍMICO' },
          { value: 'INGERIERO CIVIL BIOMEDICO', label: 'INGERIERO CIVIL BIOMEDICO' },
          { value: 'INGERIERO INDUSTRIAL', label: 'INGERIERO INDUSTRIAL' },
          { value: 'INSP.CONTROL DE CALIDAD', label: 'INSP.CONTROL DE CALIDAD' },
          { value: 'INSPECTOR', label: 'INSPECTOR' },
          { value: 'INTERPRETE EN DANZA Y COREOGRAFIA', label: 'INTERPRETE EN DANZA Y COREOGRAFIA' },
          { value: 'INTERPRETE INGLÉS - ALEMÁN', label: 'INTERPRETE INGLÉS - ALEMÁN' },
          { value: 'INTERPRETE TRADUCTOR', label: 'INTERPRETE TRADUCTOR' },
          { value: 'INVERSIONISTA', label: 'INVERSIONISTA' },
          { value: 'JEFE', label: 'JEFE' },
          { value: 'JEFE DE AREA', label: 'JEFE DE AREA' },
          { value: 'JEFE DE PROYECTOS', label: 'JEFE DE PROYECTOS' },
          { value: 'JEFE(A) ABASTECIMIENTO', label: 'JEFE(A) ABASTECIMIENTO' },
          { value: 'JEFE(A) BARRA Y GARZÓN', label: 'JEFE(A) BARRA Y GARZÓN' },
          { value: 'JEFE(A) CONTROL DE CAJA', label: 'JEFE(A) CONTROL DE CAJA' },
          { value: 'JEFE(A) DE BODEGA', label: 'JEFE(A) DE BODEGA' },
          { value: 'JEFE(A) DE COBRANZA', label: 'JEFE(A) DE COBRANZA' },
          { value: 'JEFE(A) DE LOCAL', label: 'JEFE(A) DE LOCAL' },
          { value: 'JEFE(A) DE OPERACIONES', label: 'JEFE(A) DE OPERACIONES' },
          { value: 'JEFE(A) DE PRODUCCIÓN', label: 'JEFE(A) DE PRODUCCIÓN' },
          { value: 'JEFE(A) DE PROYECTOS', label: 'JEFE(A) DE PROYECTOS' },
          { value: 'JEFE(A) DE VENTAS', label: 'JEFE(A) DE VENTAS' },
          { value: 'JEFE(A) SUCURSAL', label: 'JEFE(A) SUCURSAL' },
          { value: 'JINETE DE FINA SANGRE', label: 'JINETE DE FINA SANGRE' },
          { value: 'JUBILADO', label: 'JUBILADO' },
          { value: 'JUBILADO - RETIRADO - PENSIONADO', label: 'JUBILADO - RETIRADO - PENSIONADO' },
          { value: 'JUBILADO AGRICULTOR', label: 'JUBILADO AGRICULTOR' },
          { value: 'JUBILADO FFAA', label: 'JUBILADO FFAA' },
          { value: 'JUBILADO(A)', label: 'JUBILADO(A)' },
          { value: 'JÚNIOR', label: 'JÚNIOR' },
          { value: 'KINESIÓLOGO(A)', label: 'KINESIÓLOGO(A)' },
          { value: 'KINESIOLOGO', label: 'KINESIOLOGO' },
          { value: 'LABORATORISTA', label: 'LABORATORISTA' },
          { value: 'LABORATORISTA DENTAL', label: 'LABORATORISTA DENTAL' },
          { value: 'LIC. EN ADMINISTRACION', label: 'LIC. EN ADMINISTRACION' },
          { value: 'LIC. EN ADMINISTRACION DE RECURSOS HUMANOS', label: 'LIC. EN ADMINISTRACION DE RECURSOS HUMANOS' },
          { value: 'LIC. EN ARTES', label: 'LIC. EN ARTES' },
          { value: 'LIC. EN CIENCIA POLITICA', label: 'LIC. EN CIENCIA POLITICA' },
          { value: 'LIC. EN COMERCIO EXTERIOR', label: 'LIC. EN COMERCIO EXTERIOR' },
          { value: 'LIC. EN CONTABILIDAD', label: 'LIC. EN CONTABILIDAD' },
          { value: 'LIC. EN ESTADISTICA', label: 'LIC. EN ESTADISTICA' },
          { value: 'LIC. EN ESTUDIOS INTERNACIONALES', label: 'LIC. EN ESTUDIOS INTERNACIONALES' },
          { value: 'LIC. EN FISICA', label: 'LIC. EN FISICA' },
          { value: 'LIC. EN HISTORIA', label: 'LIC. EN HISTORIA' },
          { value: 'LIC. EN INFORMATICA', label: 'LIC. EN INFORMATICA' },
          { value: 'LIC. EN LENGUA Y LITERATURA', label: 'LIC. EN LENGUA Y LITERATURA' },
          { value: 'LIC. EN LITERATURA INGLESA', label: 'LIC. EN LITERATURA INGLESA' },
          { value: 'LIC. EN LOGISTICA', label: 'LIC. EN LOGISTICA' },
          { value: 'LIC. EN MATEMATICAS', label: 'LIC. EN MATEMATICAS' },
          { value: 'LIC. EN METEOROLOGIA', label: 'LIC. EN METEOROLOGIA' },
          { value: 'LIC. EN MUSICA', label: 'LIC. EN MUSICA' },
          { value: 'LIC. EN NUTRICION', label: 'LIC. EN NUTRICION' },
          { value: 'LIC. EN OBSTETRICIA Y PUERICULTURA', label: 'LIC. EN OBSTETRICIA Y PUERICULTURA' },
          { value: 'LIC. EN PUBLICIDAD', label: 'LIC. EN PUBLICIDAD' },
          { value: 'LIC. EN QUIMICA', label: 'LIC. EN QUIMICA' },
          { value: 'LIC. EN RELACIONES INDUSTRIALES', label: 'LIC. EN RELACIONES INDUSTRIALES' },
          { value: 'LIC. EN SEGURIDAD INDUSTRIAL', label: 'LIC. EN SEGURIDAD INDUSTRIAL' },
          { value: 'LIC. EN TRABAJO SOCIAL', label: 'LIC. EN TRABAJO SOCIAL' },
          { value: 'LIC. EN TURISMO Y/O HOTELERIA', label: 'LIC. EN TURISMO Y/O HOTELERIA' },
          { value: 'LIC. INDUSTRIAL', label: 'LIC. INDUSTRIAL' },
          { value: 'LICENCIADOEN BIOANALISIS', label: 'LICENCIADOEN BIOANALISIS' },
          { value: 'LICENCIADO', label: 'LICENCIADO' },
          { value: 'LICENCIADO(A) EN ARTES', label: 'LICENCIADO(A) EN ARTES' },
          { value: 'LICENCIADO(A) EN EDUCACIÓN', label: 'LICENCIADO(A) EN EDUCACIÓN' },
          { value: 'LICENCIADO(A) EN HISTORIA', label: 'LICENCIADO(A) EN HISTORIA' },
          { value: 'LICENCIADO(A) EN LENGUA Y LITERATURA', label: 'LICENCIADO(A) EN LENGUA Y LITERATURA' },
          { value: 'LIQUIDADOR DE SEGUROS', label: 'LIQUIDADOR DE SEGUROS' },
          { value: 'MAESTRO ALBAÑIL', label: 'MAESTRO ALBAÑIL' },
          { value: 'MAESTRO DE COCINA', label: 'MAESTRO DE COCINA' },
          { value: 'MAESTRO VIAL', label: 'MAESTRO VIAL' },
          { value: 'MAGISTER EN ADMINISTRACION', label: 'MAGISTER EN ADMINISTRACION' },
          { value: 'MAGISTER EN EDUCACION', label: 'MAGISTER EN EDUCACION' },
          { value: 'MAGISTER EN GESTION Y POLITICA CULTURAL', label: 'MAGISTER EN GESTION Y POLITICA CULTURAL' },
          { value: 'MAGISTER EN INGENIERIA AMBIENTAL', label: 'MAGISTER EN INGENIERIA AMBIENTAL' },
          { value: 'MAGISTER EN POLITICAS PUBLICAS', label: 'MAGISTER EN POLITICAS PUBLICAS' },
          { value: 'MANICURISTA', label: 'MANICURISTA' },
          { value: 'MARINO MERCANTE', label: 'MARINO MERCANTE' },
          { value: 'MARKETING', label: 'MARKETING' },
          { value: 'MASOTERAPEUTA', label: 'MASOTERAPEUTA' },
          { value: 'MATRON', label: 'MATRON' },
          { value: 'MATRON(A)', label: 'MATRON(A)' },
          { value: 'MATRONA Y PROFESOR', label: 'MATRONA Y PROFESOR' },
          { value: 'MECÁNICO', label: 'MECÁNICO' },
          { value: 'MECÁNICO AUTOMOTRIZ', label: 'MECÁNICO AUTOMOTRIZ' },
          { value: 'MECÁNICO INDUSTRIAL', label: 'MECÁNICO INDUSTRIAL' },
          { value: 'MECÁNICO MANTENCIÓN', label: 'MECÁNICO MANTENCIÓN' },
          { value: 'MECÁNICO MATRICERO', label: 'MECÁNICO MATRICERO' },
          { value: 'MECANICO AERONAUTICO', label: 'MECANICO AERONAUTICO' },
          { value: 'MÉDICO', label: 'MÉDICO' },
          { value: 'MÉDICO (ESPECIALIZADO)', label: 'MÉDICO (ESPECIALIZADO)' },
          { value: 'MÉDICO CIRUJANO', label: 'MÉDICO CIRUJANO' },
          { value: 'MÉDICO CIRUJANO - TRAUMATÓLOGO', label: 'MÉDICO CIRUJANO - TRAUMATÓLOGO' },
          { value: 'MÉDICO DERMATÓLOGO(A)', label: 'MÉDICO DERMATÓLOGO(A)' },
          { value: 'MÉDICO GENERAL', label: 'MÉDICO GENERAL' },
          { value: 'MÉDICO NEUROCIRUJANO(A)', label: 'MÉDICO NEUROCIRUJANO(A)' },
          { value: 'MÉDICO RADIÓLOGO(A)', label: 'MÉDICO RADIÓLOGO(A)' },
          { value: 'MÉDICO TRAUMATÓLOGO(A)', label: 'MÉDICO TRAUMATÓLOGO(A)' },
          { value: 'MÉDICO VETERINARIO', label: 'MÉDICO VETERINARIO' },
          { value: 'METEORÓLOGO(A)', label: 'METEORÓLOGO(A)' },
          { value: 'MICROEMPRESARIO - COMERCIANTE', label: 'MICROEMPRESARIO - COMERCIANTE' },
          { value: 'MICROEMPRESARIO(A)', label: 'MICROEMPRESARIO(A)' },
          { value: 'MICROBIOLOGO', label: 'MICROBIOLOGO' },
          { value: 'MILITAR', label: 'MILITAR' },
          { value: 'MODELO', label: 'MODELO' },
          { value: 'MOTORISTA', label: 'MOTORISTA' },
          { value: 'MÚSICO', label: 'MÚSICO' },
          { value: 'NUTRICIONISTA', label: 'NUTRICIONISTA' },
          { value: 'OBSTETRICIA', label: 'OBSTETRICIA' },
          { value: 'ODONTÓLOGO(A)', label: 'ODONTÓLOGO(A)' },
          { value: 'OFICIAL DE CARABINEROS', label: 'OFICIAL DE CARABINEROS' },
          { value: 'OFICIAL DE EJÉRCITO', label: 'OFICIAL DE EJÉRCITO' },
          { value: 'OFICIAL DE FUERZA AEREA', label: 'OFICIAL DE FUERZA AEREA' },
          { value: 'OFICIAL DE GENDARMERÍA', label: 'OFICIAL DE GENDARMERÍA' },
          { value: 'OFICIAL DE MARINA', label: 'OFICIAL DE MARINA' },
          { value: 'OFICIAL DEL EJERCITO', label: 'OFICIAL DEL EJERCITO' },
          { value: 'OFICIAL FACH', label: 'OFICIAL FACH' },
          { value: 'OFICIAL MARINA MERCANTE', label: 'OFICIAL MARINA MERCANTE' },
          { value: 'OFICIAL POLICIA DE INVESTIGACIONES', label: 'OFICIAL POLICIA DE INVESTIGACIONES' },
          { value: 'OPERADOR', label: 'OPERADOR' },
          { value: 'OPERADOR DE CALDERA', label: 'OPERADOR DE CALDERA' },
          { value: 'OPERADOR DE CARGA', label: 'OPERADOR DE CARGA' },
          { value: 'OPERADOR DE MAQ. PESADA', label: 'OPERADOR DE MAQ. PESADA' },
          { value: 'OPERADOR DE MAQUINARIA', label: 'OPERADOR DE MAQUINARIA' },
          { value: 'OPERADOR DE MAQUINARIA PESADA', label: 'OPERADOR DE MAQUINARIA PESADA' },
          { value: 'OPERADOR INFORMÁTICO', label: 'OPERADOR INFORMÁTICO' },
          { value: 'OPERADOR MAQ ALTO TONELAJE', label: 'OPERADOR MAQ ALTO TONELAJE' },
          { value: 'OPERARIO', label: 'OPERARIO' },
          { value: 'ORIENTADOR FAMILIAR', label: 'ORIENTADOR FAMILIAR' },
          { value: 'OTROS', label: 'OTROS' },
          { value: 'PAISAJISTA', label: 'PAISAJISTA' },
          { value: 'PARAMÉDICO', label: 'PARAMÉDICO' },
          { value: 'PARAMÉDICO DENTAL', label: 'PARAMÉDICO DENTAL' },
          { value: 'PARAMÉDICO ODONTOLÓGICO', label: 'PARAMÉDICO ODONTOLÓGICO' },
          { value: 'PARTICULAR', label: 'PARTICULAR' },
          { value: 'PASTELERO', label: 'PASTELERO' },
          { value: 'PASTOR', label: 'PASTOR' },
          { value: 'PATRÓN DE PESCA', label: 'PATRÓN DE PESCA' },
          { value: 'PEDAGOGÍA BÁSICA', label: 'PEDAGOGÍA BÁSICA' },
          { value: 'PELUQUERO(A)', label: 'PELUQUERO(A)' },
          { value: 'PENSIONADO', label: 'PENSIONADO' },
          { value: 'PENSIONADO DE LA FFAA', label: 'PENSIONADO DE LA FFAA' },
          { value: 'PENSIONADO(A)', label: 'PENSIONADO(A)' },
          { value: 'PERITO FOTÓGRAFO', label: 'PERITO FOTÓGRAFO' },
          { value: 'PERIODISMO', label: 'PERIODISMO' },
          { value: 'PERIODISTA', label: 'PERIODISTA' },
          { value: 'PILOTO', label: 'PILOTO' },
          { value: 'PODÓLOGO(A)', label: 'PODÓLOGO(A)' },
          { value: 'PREVENCIONISTA', label: 'PREVENCIONISTA' },
          { value: 'PROCURADOR', label: 'PROCURADOR' },
          { value: 'PRODUCTOR', label: 'PRODUCTOR' },
          { value: 'PRODUCTOR AUDIOVISUAL', label: 'PRODUCTOR AUDIOVISUAL' },
          { value: 'PRODUCTOR DE EVENTOS', label: 'PRODUCTOR DE EVENTOS' },
          { value: 'PRODUCTOR DE TV', label: 'PRODUCTOR DE TV' },
          { value: 'PRODUCTOR GRAFICO', label: 'PRODUCTOR GRAFICO' },
          { value: 'PROFESIONAL INDEPENDIENTE', label: 'PROFESIONAL INDEPENDIENTE' },
          { value: 'PROFESIONAL TÉCNICO', label: 'PROFESIONAL TÉCNICO' },
          { value: 'PROFESOR', label: 'PROFESOR' },
          { value: 'PROFESOR(A) DE BIOLOGÍA', label: 'PROFESOR(A) DE BIOLOGÍA' },
          { value: 'PROFESOR(A) DE ECUACIÓN DIFERENCIAL', label: 'PROFESOR(A) DE ECUACIÓN DIFERENCIAL' },
          { value: 'PROFESOR(A) DE EDUCACIÓN FÍSICA', label: 'PROFESOR(A) DE EDUCACIÓN FÍSICA' },
          { value: 'PROFESOR(A) DE ENSEÑANZA MEDIA', label: 'PROFESOR(A) DE ENSEÑANZA MEDIA' },
          { value: 'PROFESOR(A) DE ESTADO', label: 'PROFESOR(A) DE ESTADO' },
          { value: 'PROFESOR(A) DE INGLÉS', label: 'PROFESOR(A) DE INGLÉS' },
          { value: 'PROFESOR(A) EDUCACIÓN BÁSICA', label: 'PROFESOR(A) EDUCACIÓN BÁSICA' },
          { value: 'PROFESOR(A) HIS. Y GEO. DE CHILE', label: 'PROFESOR(A) HIS. Y GEO. DE CHILE' },
          { value: 'PROFESOR(A) JEFE', label: 'PROFESOR(A) JEFE' },
          { value: 'PROFESOR(A) LICENCIADO - CONTADOR', label: 'PROFESOR(A) LICENCIADO - CONTADOR' },
          { value: 'PROFESOR(A) PENSIONADA', label: 'PROFESOR(A) PENSIONADA' },
          { value: 'PROGRAMADOR', label: 'PROGRAMADOR' },
          { value: 'PROGRAMADOR ANALISTA', label: 'PROGRAMADOR ANALISTA' },
          { value: 'PROGRAMADOR COMPUTACIONAL', label: 'PROGRAMADOR COMPUTACIONAL' },
          { value: 'PROYECTISTA', label: 'PROYECTISTA' },
          { value: 'PSICÓLOGO', label: 'PSICÓLOGO' },
          { value: 'PSICOPEDAGOGO', label: 'PSICOPEDAGOGO' },
          { value: 'PSICOPEDAGOGO(A)', label: 'PSICOPEDAGOGO(A)' },
          { value: 'PSICOPEDAGOGO(A) ED DIF', label: 'PSICOPEDAGOGO(A) ED DIF' },
          { value: 'PSIQUIATRA', label: 'PSIQUIATRA' },
          { value: 'PUBLICISTA', label: 'PUBLICISTA' },
          { value: 'QUÍMICO', label: 'QUÍMICO' },
          { value: 'QUÍMICO ANALISTA', label: 'QUÍMICO ANALISTA' },
          { value: 'QUÍMICO FARMACÉUTICO', label: 'QUÍMICO FARMACÉUTICO' },
          { value: 'QUÍMICO NUCLEAR', label: 'QUÍMICO NUCLEAR' },
          { value: 'QUIMICO', label: 'QUIMICO' },
          { value: 'QUIROPRACTICO', label: 'QUIROPRACTICO' },
          { value: 'RADIOLOGO', label: 'RADIOLOGO' },
          { value: 'REALIZADOR AUDIOVISUAL', label: 'REALIZADOR AUDIOVISUAL' },
          { value: 'RECAUDADOR(A)', label: 'RECAUDADOR(A)' },
          { value: 'RELACIONADOR PUBLICO', label: 'RELACIONADOR PUBLICO' },
          { value: 'RELACIONADOR(A) PÚBLICO', label: 'RELACIONADOR(A) PÚBLICO' },
          { value: 'RELIGIOSO(A)', label: 'RELIGIOSO(A)' },
          { value: 'RENTISTA', label: 'RENTISTA' },
          { value: 'REPRESENTANTE DE VENTAS', label: 'REPRESENTANTE DE VENTAS' },
          { value: 'SECRETARIA', label: 'SECRETARIA' },
          { value: 'SECRETARIA ADMINISTRATIVA', label: 'SECRETARIA ADMINISTRATIVA' },
          { value: 'SECRETARIA BILINGUE', label: 'SECRETARIA BILINGUE' },
          { value: 'SECRETARIA COMERCIO EXTERIOR', label: 'SECRETARIA COMERCIO EXTERIOR' },
          { value: 'SECRETARIA COMPUTACIONAL', label: 'SECRETARIA COMPUTACIONAL' },
          { value: 'SECRETARIA EJECUTIVA', label: 'SECRETARIA EJECUTIVA' },
          { value: 'SECRETARIA EJECUTIVA COMPUTACIONAL', label: 'SECRETARIA EJECUTIVA COMPUTACIONAL' },
          { value: 'SECRETARIA EJECUTIVO BILINGÜE', label: 'SECRETARIA EJECUTIVO BILINGÜE' },
          { value: 'SECRETARIA GERENCIA', label: 'SECRETARIA GERENCIA' },
          { value: 'SERVICIOS', label: 'SERVICIOS' },
          { value: 'SIN PROFESION U OFICIO DECLARADO', label: 'SIN PROFESION U OFICIO DECLARADO' },
          { value: 'SOBRECARGO', label: 'SOBRECARGO' },
          { value: 'SOCIO', label: 'SOCIO' },
          { value: 'SOCIÓLOGO', label: 'SOCIÓLOGO' },
          { value: 'SOLDADOR', label: 'SOLDADOR' },
          { value: 'SONIDISTA', label: 'SONIDISTA' },
          { value: 'SOSTENEDORA', label: 'SOSTENEDORA' },
          { value: 'SUB JEFE(A) DE LOGÍSTICA', label: 'SUB JEFE(A) DE LOGÍSTICA' },
          { value: 'SUBGERENTE', label: 'SUBGERENTE' },
          { value: 'SUPERVISOR', label: 'SUPERVISOR' },
          { value: 'SUPERVISOR DE OBRAS', label: 'SUPERVISOR DE OBRAS' },
          { value: 'SUPERVISOR(A)', label: 'SUPERVISOR(A)' },
          { value: 'SUPERVISOR(A) ADMINISTRATIVO', label: 'SUPERVISOR(A) ADMINISTRATIVO' },
          { value: 'SUPERVISOR(A) DE AÉREA', label: 'SUPERVISOR(A) DE AÉREA' },
          { value: 'SUPERVISOR(A) DE PROCESOS PRODUCTIVOS', label: 'SUPERVISOR(A) DE PROCESOS PRODUCTIVOS' },
          { value: 'SUPERVISOR(A) TÉCNICO', label: 'SUPERVISOR(A) TÉCNICO' },
          { value: 'TECNICO', label: 'TECNICO' },
          { value: 'TECNICO ANALISTA QUIMICO', label: 'TECNICO ANALISTA QUIMICO' },
          { value: 'TECNICO EN ADMINISTRADOR DE EMPRESAS', label: 'TECNICO EN ADMINISTRADOR DE EMPRESAS' },
          { value: 'TECNICO EN AERONAUTICA', label: 'TECNICO EN AERONAUTICA' },
          { value: 'TECNICO EN AGRICULTURA', label: 'TECNICO EN AGRICULTURA' },
          { value: 'TECNICO EN ALIMENTOS', label: 'TECNICO EN ALIMENTOS' },
          { value: 'TECNICO EN ANALISIS Y DISEÑO DE SISTEMA', label: 'TECNICO EN ANALISIS Y DISEÑO DE SISTEMA' },
          { value: 'TECNICO EN CIBER SEGURIDAD', label: 'TECNICO EN CIBER SEGURIDAD' },
          { value: 'TECNICO EN COCINA INTERNACIONAL', label: 'TECNICO EN COCINA INTERNACIONAL' },
          { value: 'TECNICO EN CONECTIVIDAD Y REDES', label: 'TECNICO EN CONECTIVIDAD Y REDES' },
          { value: 'TECNICO EN CONTABILIDAD', label: 'TECNICO EN CONTABILIDAD' },
          { value: 'TECNICO EN CONTROL DE CALIDAD', label: 'TECNICO EN CONTROL DE CALIDAD' },
          { value: 'TECNICO EN CONTROL INDUSTRIAL', label: 'TECNICO EN CONTROL INDUSTRIAL' },
          { value: 'TECNICO EN DECORACION DE INTERIORES', label: 'TECNICO EN DECORACION DE INTERIORES' },
          { value: 'TECNICO EN DIBUJO INDUSTRIAL', label: 'TECNICO EN DIBUJO INDUSTRIAL' },
          { value: 'TECNICO EN DISEÑO GRAFICO', label: 'TECNICO EN DISEÑO GRAFICO' },
          { value: 'TECNICO EN ELECTRICIDAD', label: 'TECNICO EN ELECTRICIDAD' },
          { value: 'TECNICO EN ELECTRONICA', label: 'TECNICO EN ELECTRONICA' },
          { value: 'TECNICO EN ENERGIAS RENOVABLES', label: 'TECNICO EN ENERGIAS RENOVABLES' },
          { value: 'TECNICO EN EQUIPO MINERO', label: 'TECNICO EN EQUIPO MINERO' },
          { value: 'TECNICO EN ESTRUCTURAS', label: 'TECNICO EN ESTRUCTURAS' },
          { value: 'TECNICO EN FARMACIA', label: 'TECNICO EN FARMACIA' },
          { value: 'TECNICO EN FINANZAS', label: 'TECNICO EN FINANZAS' },
          { value: 'TECNICO EN FOTOGRAFIA', label: 'TECNICO EN FOTOGRAFIA' },
          { value: 'TECNICO EN GESTION LOGISTICA', label: 'TECNICO EN GESTION LOGISTICA' },
          { value: 'TECNICO EN HIGIENE Y SEGURIDAD', label: 'TECNICO EN HIGIENE Y SEGURIDAD' },
          { value: 'TECNICO EN IMAGENOLOGIA', label: 'TECNICO EN IMAGENOLOGIA' },
          { value: 'TECNICO EN INFORMATICA', label: 'TECNICO EN INFORMATICA' },
          { value: 'TECNICO EN INSTALACIONES DE GAS', label: 'TECNICO EN INSTALACIONES DE GAS' },
          { value: 'TECNICO EN INSTRUMENTACION', label: 'TECNICO EN INSTRUMENTACION' },
          { value: 'TECNICO EN LOGISTICA', label: 'TECNICO EN LOGISTICA' },
          { value: 'TECNICO EN MANTENIMIENTO AERONAUTICO', label: 'TECNICO EN MANTENIMIENTO AERONAUTICO' },
          { value: 'TECNICO EN MAQUINARIA PESADA', label: 'TECNICO EN MAQUINARIA PESADA' },
          { value: 'TECNICO EN MECANICA', label: 'TECNICO EN MECANICA' },
          { value: 'TECNICO EN MINERIA', label: 'TECNICO EN MINERIA' },
          { value: 'TECNICO EN MODELAMIENTO ARQUITECTONICO', label: 'TECNICO EN MODELAMIENTO ARQUITECTONICO' },
          { value: 'TECNICO EN OBRAS', label: 'TECNICO EN OBRAS' },
          { value: 'TECNICO EN ODONTOLOGIA', label: 'TECNICO EN ODONTOLOGIA' },
          { value: 'TECNICO EN OPERACION DE MAQUINARIA', label: 'TECNICO EN OPERACION DE MAQUINARIA' },
          { value: 'TECNICO EN OPERACIONES LOGISTICAS', label: 'TECNICO EN OPERACIONES LOGISTICAS' },
          { value: 'TECNICO EN OPERACIONES MINERAS', label: 'TECNICO EN OPERACIONES MINERAS' },
          { value: 'TECNICO EN PREVENCION DE RIESGO', label: 'TECNICO EN PREVENCION DE RIESGO' },
          { value: 'TECNICO EN PREVENCION DE RIESGOS', label: 'TECNICO EN PREVENCION DE RIESGOS' },
          { value: 'TECNICO EN PROGRAMACION', label: 'TECNICO EN PROGRAMACION' },
          { value: 'TECNICO EN PUBLICIDAD', label: 'TECNICO EN PUBLICIDAD' },
          { value: 'TECNICO EN QUIMICA', label: 'TECNICO EN QUIMICA' },
          { value: 'TECNICO EN RADIODIAGNOSTICO Y RADIOTERAPIA', label: 'TECNICO EN RADIODIAGNOSTICO Y RADIOTERAPIA' },
          { value: 'TECNICO EN REHABILITACION', label: 'TECNICO EN REHABILITACION' },
          { value: 'TECNICO EN RELACIONES PUBLICAS', label: 'TECNICO EN RELACIONES PUBLICAS' },
          { value: 'TECNICO EN RIESGO Y SEGUROS', label: 'TECNICO EN RIESGO Y SEGUROS' },
          { value: 'TECNICO EN SEGURIDAD AEROPORTUARIA', label: 'TECNICO EN SEGURIDAD AEROPORTUARIA' },
          { value: 'TECNICO EN TELECOMUNICACIONES', label: 'TECNICO EN TELECOMUNICACIONES' },
          { value: 'TECNICO EN TRABAJO SOCIAL', label: 'TECNICO EN TRABAJO SOCIAL' },
          { value: 'TECNICO EN TRASPORTE', label: 'TECNICO EN TRASPORTE' },
          { value: 'TECNICO EN TURISMO Y/O HOTELERIA', label: 'TECNICO EN TURISMO Y/O HOTELERIA' },
          { value: 'TECNICO LABORATORISTA DENTAL', label: 'TECNICO LABORATORISTA DENTAL' },
          { value: 'TECNICO MARITIMO PORTUARIO', label: 'TECNICO MARITIMO PORTUARIO' },
          { value: 'TECNICO MECANICO INDUSTRIAL', label: 'TECNICO MECANICO INDUSTRIAL' },
          { value: 'TECNICO OPTICO INDUSTRIAL', label: 'TECNICO OPTICO INDUSTRIAL' },
          { value: 'TECNICO VETERINARIO', label: 'TECNICO VETERINARIO' },
          { value: 'TÉCNICO ADMINISTRACIÓN DE EMPRESAS', label: 'TÉCNICO ADMINISTRACIÓN DE EMPRESAS' },
          { value: 'TÉCNICO ADMINISTRATIVO', label: 'TÉCNICO ADMINISTRATIVO' },
          { value: 'TÉCNICO AGRÍCOLA', label: 'TÉCNICO AGRÍCOLA' },
          { value: 'TÉCNICO AGROPECUARIO', label: 'TÉCNICO AGROPECUARIO' },
          { value: 'TÉCNICO AUTOMOTRIZ', label: 'TÉCNICO AUTOMOTRIZ' },
          { value: 'TÉCNICO AXILIAR LAB ADN', label: 'TÉCNICO AXILIAR LAB ADN' },
          { value: 'TÉCNICO COCINA INTERNACIONAL', label: 'TÉCNICO COCINA INTERNACIONAL' },
          { value: 'TÉCNICO CONTABLE', label: 'TÉCNICO CONTABLE' },
          { value: 'TÉCNICO ELÉCTRICO', label: 'TÉCNICO ELÉCTRICO' },
          { value: 'TÉCNICO ELÉCTRICO INDUSTRIAL', label: 'TÉCNICO ELÉCTRICO INDUSTRIAL' },
          { value: 'TÉCNICO ELECTRO MECÁNICO', label: 'TÉCNICO ELECTRO MECÁNICO' },
          { value: 'TÉCNICO EN ADMINISTRACIÓN', label: 'TÉCNICO EN ADMINISTRACIÓN' },
          { value: 'TÉCNICO EN ADMINISTRACIÓN DE EMPRESAS', label: 'TÉCNICO EN ADMINISTRACIÓN DE EMPRESAS' },
          { value: 'TÉCNICO EN ADMINISTRACIÓN DE PERSONAL', label: 'TÉCNICO EN ADMINISTRACIÓN DE PERSONAL' },
          { value: 'TÉCNICO EN ADMINISTRACIÓN HOTELERA', label: 'TÉCNICO EN ADMINISTRACIÓN HOTELERA' },
          { value: 'TÉCNICO EN AUTOMATIZACIÓN', label: 'TÉCNICO EN AUTOMATIZACIÓN' },
          { value: 'TÉCNICO EN BIENESTAR', label: 'TÉCNICO EN BIENESTAR' },
          { value: 'TÉCNICO EN CIENCIAS CRIMINALISTICA', label: 'TÉCNICO EN CIENCIAS CRIMINALISTICA' },
          { value: 'TÉCNICO EN COMERCIO', label: 'TÉCNICO EN COMERCIO' },
          { value: 'TÉCNICO EN COMERCIO EXTERIOR', label: 'TÉCNICO EN COMERCIO EXTERIOR' },
          { value: 'TÉCNICO EN COMPUTACIÓN', label: 'TÉCNICO EN COMPUTACIÓN' },
          { value: 'TÉCNICO EN CONSTRUCCIÓN', label: 'TÉCNICO EN CONSTRUCCIÓN' },
          { value: 'TÉCNICO EN DISEÑO PUBLICITARIO', label: 'TÉCNICO EN DISEÑO PUBLICITARIO' },
          { value: 'TÉCNICO EN EDUCACIÓN PARVULARIA', label: 'TÉCNICO EN EDUCACIÓN PARVULARIA' },
          { value: 'TÉCNICO EN ELECTRÓNICA INDUSTRIAL', label: 'TÉCNICO EN ELECTRÓNICA INDUSTRIAL' },
          { value: 'TÉCNICO EN ENFERMERÍA', label: 'TÉCNICO EN ENFERMERÍA' },
          { value: 'TÉCNICO EN GASTRONOMÍA', label: 'TÉCNICO EN GASTRONOMÍA' },
          { value: 'TÉCNICO EN MANTENCIÓN', label: 'TÉCNICO EN MANTENCIÓN' },
          { value: 'TÉCNICO EN MARKETING', label: 'TÉCNICO EN MARKETING' },
          { value: 'TÉCNICO EN PRODUCCIÓN GASTRONÓMICA', label: 'TÉCNICO EN PRODUCCIÓN GASTRONÓMICA' },
          { value: 'TÉCNICO EN RECURSOS HUMANOS', label: 'TÉCNICO EN RECURSOS HUMANOS' },
          { value: 'TÉCNICO EN REFRIGERACIÓN', label: 'TÉCNICO EN REFRIGERACIÓN' },
          { value: 'TÉCNICO EN SEGURIDAD', label: 'TÉCNICO EN SEGURIDAD' },
          { value: 'TÉCNICO EN SERVICIO DE VUELO', label: 'TÉCNICO EN SERVICIO DE VUELO' },
          { value: 'TÉCNICO EN SERVICIO TÉCNICO', label: 'TÉCNICO EN SERVICIO TÉCNICO' },
          { value: 'TÉCNICO EN SONIDO', label: 'TÉCNICO EN SONIDO' },
          { value: 'TÉCNICO EN TURISMO', label: 'TÉCNICO EN TURISMO' },
          { value: 'TÉCNICO EN TURISMO BILINGUE', label: 'TÉCNICO EN TURISMO BILINGUE' },
          { value: 'TÉCNICO EN TURISMO Y HOTELERIA', label: 'TÉCNICO EN TURISMO Y HOTELERIA' },
          { value: 'TÉCNICO ENFERMARÍA', label: 'TÉCNICO ENFERMARÍA' },
          { value: 'TÉCNICO FINANCIERO', label: 'TÉCNICO FINANCIERO' },
          { value: 'TÉCNICO FORESTAL', label: 'TÉCNICO FORESTAL' },
          { value: 'TÉCNICO GASTRONÓMICO INTERNACIONAL', label: 'TÉCNICO GASTRONÓMICO INTERNACIONAL' },
          { value: 'TÉCNICO GRÁFICO', label: 'TÉCNICO GRÁFICO' },
          { value: 'TÉCNICO INDUSTRIAL', label: 'TÉCNICO INDUSTRIAL' },
          { value: 'TÉCNICO INFORMÁTICO', label: 'TÉCNICO INFORMÁTICO' },
          { value: 'TÉCNICO JURÍDICO', label: 'TÉCNICO JURÍDICO' },
          { value: 'TÉCNICO MECÁNICO', label: 'TÉCNICO MECÁNICO' },
          { value: 'TÉCNICO MECÁNICO AUTOMOTRIZ', label: 'TÉCNICO MECÁNICO AUTOMOTRIZ' },
          { value: 'TÉCNICO PARAMÉDICO', label: 'TÉCNICO PARAMÉDICO' },
          { value: 'TÉCNICO PLANIFICACIÓN SOCIAL', label: 'TÉCNICO PLANIFICACIÓN SOCIAL' },
          { value: 'TÉCNICO QUÍMICO', label: 'TÉCNICO QUÍMICO' },
          { value: 'TÉCNICO SOLDADURAS', label: 'TÉCNICO SOLDADURAS' },
          { value: 'TÉCNICO SUPERIOR EN INFORMÁTICA', label: 'TÉCNICO SUPERIOR EN INFORMÁTICA' },
          { value: 'TÉCNICO UNIVERSITARIO', label: 'TÉCNICO UNIVERSITARIO' },
          { value: 'TÉCNICO UNIVERSITARIO EN ELECTRICIDAD', label: 'TÉCNICO UNIVERSITARIO EN ELECTRICIDAD' },
          { value: 'TÉCNICO VETERINARIA', label: 'TÉCNICO VETERINARIA' },
          { value: 'TECNICO ADMINISTRATIVO', label: 'TECNICO ADMINISTRATIVO' },
          { value: 'TECNCO EN HIDRONEUMATICA', label: 'TECNCO EN HIDRONEUMATICA' },
          { value: 'TECNOLOGO', label: 'TECNOLOGO' },
          { value: 'TECNOLOGO EN ADMINISTRACION', label: 'TECNOLOGO EN ADMINISTRACION' },
          { value: 'TECNOLOGO EN ALIMENTOS', label: 'TECNOLOGO EN ALIMENTOS' },
          { value: 'TECNOLOGO EN CONSTRUCCION', label: 'TECNOLOGO EN CONSTRUCCION' },
          { value: 'TECNOLOGO EN MANTENIMIENTO INDUSTRIAL', label: 'TECNOLOGO EN MANTENIMIENTO INDUSTRIAL' },
          { value: 'TECNOLOGO MEDICO', label: 'TECNOLOGO MEDICO' },
          { value: 'TECNÓLOGA EN ALIMENTOS', label: 'TECNÓLOGA EN ALIMENTOS' },
          { value: 'TECNÓLOGO(A) MEDICO', label: 'TECNÓLOGO(A) MEDICO' },
          { value: 'TELEOPERADOR(A)', label: 'TELEOPERADOR(A)' },
          { value: 'TERAPEUTA', label: 'TERAPEUTA' },
          { value: 'TERAPEUTA EN ADICCIONES', label: 'TERAPEUTA EN ADICCIONES' },
          { value: 'TERAPEUTA FAMILIAR', label: 'TERAPEUTA FAMILIAR' },
          { value: 'TERAPEUTA OCUPACIONAL', label: 'TERAPEUTA OCUPACIONAL' },
          { value: 'TESORERO(A)', label: 'TESORERO(A)' },
          { value: 'TIPÓGRAFO', label: 'TIPÓGRAFO' },
          { value: 'TOPOGRAFIA', label: 'TOPOGRAFIA' },
          { value: 'TOPOGRAFO', label: 'TOPOGRAFO' },
          { value: 'TRABAJADOR SOCIAL', label: 'TRABAJADOR SOCIAL' },
          { value: 'TRADUCTOR O INTERPRETE', label: 'TRADUCTOR O INTERPRETE' },
          { value: 'TRADUCTOR(A)', label: 'TRADUCTOR(A)' },
          { value: 'TRADUCTOR(A) DE INTERPRETES', label: 'TRADUCTOR(A) DE INTERPRETES' },
          { value: 'TRADUCTOR(A) INGLÉS', label: 'TRADUCTOR(A) INGLÉS' },
          { value: 'TRADUCTOR(A) INTERPRETE', label: 'TRADUCTOR(A) INTERPRETE' },
          { value: 'TRANSPORTISTA', label: 'TRANSPORTISTA' },
          { value: 'TRANSPORTISTA ESCOLAR', label: 'TRANSPORTISTA ESCOLAR' },
          { value: 'TRIPULANTE', label: 'TRIPULANTE' },
          { value: 'TRIPULANTE CABINA', label: 'TRIPULANTE CABINA' },
          { value: 'TRIPULANTE DE CABINA', label: 'TRIPULANTE DE CABINA' },
          { value: 'VENDEDOR', label: 'VENDEDOR' },
          { value: 'VENDEDOR(A)', label: 'VENDEDOR(A)' },
          { value: 'VENDEDOR(A) ÓPTICO', label: 'VENDEDOR(A) ÓPTICO' },
          { value: 'VISITADOR MEDICO', label: 'VISITADOR MEDICO' },
          { value: 'VISITADOR(A) MEDICO', label: 'VISITADOR(A) MEDICO' },
        ],
      },
      { key: 'telefonoCelular',  label: 'Teléfono celular',   type: 'phone', required: true },
      { key: 'correoElectronico',label: 'Correo electrónico', type: 'email', required: true },
    ],
  };
}
