import type { SelectOption } from '../types';

// Datos extraídos directamente del portal Cubit de Imagina (nuevocliente.asp).
// Los `value` son los mismos códigos que usa el <select> del portal, así el
// script selecciona por valor y no depende de que el texto calce.

export const REGIONES: SelectOption[] = [
  { value: '15', label: 'Región de Arica y Parinacota' },
  { value: '1',  label: 'Región de Tarapacá' },
  { value: '2',  label: 'Región de Antofagasta' },
  { value: '3',  label: 'Región de Atacama' },
  { value: '4',  label: 'Región de Coquimbo' },
  { value: '5',  label: 'Región de Valparaíso' },
  { value: '13', label: 'Región Metropolitana' },
  { value: '6',  label: "Región del Libertador General Bernardo O'Higgins" },
  { value: '7',  label: 'Región del Maule' },
  { value: '8',  label: 'Región del Biobío' },
  { value: '9',  label: 'Región de La Araucanía' },
  { value: '14', label: 'Región de Los Ríos' },
  { value: '10', label: 'Región de Los Lagos' },
  { value: '11', label: 'Región de Aysén del General Carlos Ibáñez del Campo' },
  { value: '12', label: 'Región de Magallanes y de la Antártica Chilena' },
];

/** Comunas que ofrece el portal para cada región (clave = value de la región). */
export const COMUNAS_POR_REGION: Record<string, SelectOption[]> = {
  // Tarapacá
  '1': [
    { value: '13606', label: 'Alto Hospicio' },
    { value: '1102',  label: 'Camiña' },
    { value: '1103',  label: 'Colchane' },
    { value: '1104',  label: 'Huara' },
    { value: '1101',  label: 'Iquique' },
    { value: '1105',  label: 'Pica' },
    { value: '1106',  label: 'Pozo Almonte' },
  ],
  // Antofagasta
  '2': [
    { value: '2101', label: 'Antofagasta' },
    { value: '2201', label: 'Calama' },
    { value: '2302', label: 'María Elena' },
    { value: '2102', label: 'Mejillones' },
    { value: '2202', label: 'Ollagüe' },
    { value: '2203', label: 'San Pedro de Atacama' },
    { value: '2103', label: 'Sierra' },
    { value: '2104', label: 'Taltal' },
    { value: '2301', label: 'Tocopilla' },
  ],
  // Atacama
  '3': [
    { value: '3302', label: 'Alto del Carmen' },
    { value: '3102', label: 'Caldera' },
    { value: '3201', label: 'Chañaral' },
    { value: '3101', label: 'Copiapó' },
    { value: '3202', label: 'Diego de Almagro' },
    { value: '3303', label: 'Freirina' },
    { value: '3304', label: 'Huasco' },
    { value: '3103', label: 'Tierra Amarilla' },
    { value: '3301', label: 'Vallenar' },
  ],
  // Coquimbo
  '4': [
    { value: '4103', label: 'Andacollo' },
    { value: '4202', label: 'Canela' },
    { value: '4302', label: 'Combarbalá' },
    { value: '4102', label: 'Coquimbo' },
    { value: '4201', label: 'Illapel' },
    { value: '4104', label: 'La Higuera' },
    { value: '4101', label: 'La Serena' },
    { value: '4203', label: 'Los Vilos' },
    { value: '4303', label: 'Monte Patria' },
    { value: '4301', label: 'Ovalle' },
    { value: '4105', label: 'Paiguano' },
    { value: '4304', label: 'Punitaqui' },
    { value: '4305', label: 'Río Hurtado' },
    { value: '4204', label: 'Salamanca' },
    { value: '4106', label: 'Vicuña' },
  ],
  // Valparaíso
  '5': [
    { value: '5602', label: 'Algarrobo' },
    { value: '5402', label: 'Cabildo' },
    { value: '5502', label: 'Calera' },
    { value: '5302', label: 'Calle Larga' },
    { value: '5603', label: 'Cartagena' },
    { value: '5102', label: 'Casablanca' },
    { value: '5702', label: 'Catemu' },
    { value: '5103', label: 'Concon' },
    { value: '5604', label: 'El Quisco' },
    { value: '5605', label: 'El Tabo' },
    { value: '5503', label: 'Hijuelas' },
    { value: '5201', label: 'Isla de Pascua' },
    { value: '5104', label: 'Juan Fernández' },
    { value: '5504', label: 'La Cruz' },
    { value: '5401', label: 'La Ligua' },
    { value: '5505', label: 'Limache' },
    { value: '5703', label: 'Llaillay' },
    { value: '5301', label: 'Los Andes' },
    { value: '5506', label: 'Nogales' },
    { value: '5507', label: 'Olmué' },
    { value: '5704', label: 'Panquehue' },
    { value: '5403', label: 'Papudo' },
    { value: '5404', label: 'Petorca' },
    { value: '5105', label: 'Puchuncaví' },
    { value: '5705', label: 'Putaendo' },
    { value: '5501', label: 'Quillota' },
    { value: '5106', label: 'Quilpué' },
    { value: '5107', label: 'Quintero' },
    { value: '5303', label: 'Rinconada' },
    { value: '5601', label: 'San Antonio' },
    { value: '5304', label: 'San Esteban' },
    { value: '5701', label: 'San Felipe' },
    { value: '5706', label: 'Santa María' },
    { value: '5606', label: 'Santo Domingo' },
    { value: '5101', label: 'Valparaíso' },
    { value: '5108', label: 'Villa Alemana' },
    { value: '5109', label: 'Viña del Mar' },
    { value: '5405', label: 'Zapallar' },
  ],
  // O'Higgins
  '6': [
    { value: '6302', label: 'Chepica' },
    { value: '6303', label: 'Chimbarongo' },
    { value: '6102', label: 'Codegua' },
    { value: '6103', label: 'Coinco' },
    { value: '6104', label: 'Coltauco' },
    { value: '6105', label: 'Doñihue' },
    { value: '6106', label: 'Graneros' },
    { value: '6202', label: 'La Estrella' },
    { value: '6107', label: 'Las Cabras' },
    { value: '6203', label: 'Litueche' },
    { value: '6304', label: 'Lolol' },
    { value: '6108', label: 'Machalí' },
    { value: '6109', label: 'Malloa' },
    { value: '6204', label: 'Marchihue' },
    { value: '6110', label: 'Mostazal' },
    { value: '6305', label: 'Nancagua' },
    { value: '6205', label: 'Navidad' },
    { value: '6111', label: 'Olivar' },
    { value: '6306', label: 'Palmilla' },
    { value: '6206', label: 'Paredones' },
    { value: '6307', label: 'Peralillo' },
    { value: '6112', label: 'Peumo' },
    { value: '6113', label: 'Pichidegua' },
    { value: '6201', label: 'Pichilemu' },
    { value: '6308', label: 'Placilla' },
    { value: '6309', label: 'Pumanque' },
    { value: '6114', label: 'Quinta de Tilcoco' },
    { value: '6101', label: 'Rancagua' },
    { value: '6115', label: 'Rengo' },
    { value: '6116', label: 'Requínoa' },
    { value: '6301', label: 'San Fernando' },
    { value: '6117', label: 'San Vicente' },
    { value: '6310', label: 'Santa Cruz' },
  ],
  // Maule
  '7': [
    { value: '7201', label: 'Cauquenes' },
    { value: '7202', label: 'Chanco' },
    { value: '7402', label: 'Colbún' },
    { value: '7102', label: 'Constitución' },
    { value: '7103', label: 'Curepto' },
    { value: '7301', label: 'Curicó' },
    { value: '7104', label: 'Empedrado' },
    { value: '7302', label: 'Hualañé' },
    { value: '7303', label: 'Licantén' },
    { value: '7401', label: 'Linares' },
    { value: '7403', label: 'Longaví' },
    { value: '7105', label: 'Maule' },
    { value: '7304', label: 'Molina' },
    { value: '7404', label: 'Parral' },
    { value: '7106', label: 'Pelarco' },
    { value: '7203', label: 'Pelluhue' },
    { value: '7107', label: 'Pencahue' },
    { value: '7305', label: 'Rauco' },
    { value: '7405', label: 'Retiro' },
    { value: '7108', label: 'Río Claro' },
    { value: '7306', label: 'Romeral' },
    { value: '7307', label: 'Sagrada Familia' },
    { value: '7109', label: 'San Clemente' },
    { value: '7406', label: 'San Javier' },
    { value: '7110', label: 'San Rafael' },
    { value: '7101', label: 'Talca' },
    { value: '7308', label: 'Teno' },
    { value: '7309', label: 'Vichuquén' },
    { value: '7407', label: 'Villa Alegre' },
    { value: '7408', label: 'Yerbas Buenas' },
  ],
  // Biobío (el portal incluye aquí las comunas de Ñuble)
  '8': [
    { value: '8302', label: 'Antuco' },
    { value: '8202', label: 'Arauco' },
    { value: '8402', label: 'Bulnes' },
    { value: '8303', label: 'Cabrero' },
    { value: '8203', label: 'Cañete' },
    { value: '8103', label: 'Chiguayante' },
    { value: '8401', label: 'Chillán' },
    { value: '8406', label: 'Chillán Viejo' },
    { value: '8403', label: 'Cobquecura' },
    { value: '8404', label: 'Coelemu' },
    { value: '8405', label: 'Coihueco' },
    { value: '8101', label: 'Concepción' },
    { value: '8204', label: 'Contulmo' },
    { value: '8102', label: 'Coronel' },
    { value: '8205', label: 'Curanilahue' },
    { value: '8407', label: 'El Carmen' },
    { value: '8104', label: 'Florida' },
    { value: '8112', label: 'Hualpén' },
    { value: '8105', label: 'Hualqui' },
    { value: '8304', label: 'Laja' },
    { value: '8201', label: 'Lebu' },
    { value: '8206', label: 'Los Alamos' },
    { value: '8301', label: 'Los Angeles' },
    { value: '8106', label: 'Lota' },
    { value: '8305', label: 'Mulchén' },
    { value: '8306', label: 'Nacimiento' },
    { value: '8307', label: 'Negrete' },
    { value: '8408', label: 'Ninhue' },
    { value: '8409', label: 'Ñiquén' },
    { value: '8410', label: 'Pemuco' },
    { value: '8107', label: 'Penco' },
    { value: '8411', label: 'Pinto' },
    { value: '8412', label: 'Portezuelo' },
    { value: '8308', label: 'Quilaco' },
    { value: '8309', label: 'Quilleco' },
    { value: '8413', label: 'Quillón' },
    { value: '8414', label: 'Quirihue' },
    { value: '8415', label: 'Ránquil' },
    { value: '8416', label: 'San Carlos' },
    { value: '8417', label: 'San Fabián' },
    { value: '8418', label: 'San Ignacio' },
    { value: '8419', label: 'San Nicolás' },
    { value: '8108', label: 'San Pedro de la Paz' },
    { value: '8310', label: 'San Rosendo' },
    { value: '8109', label: 'Santa' },
    { value: '8311', label: 'Santa Bárbara' },
    { value: '8110', label: 'Talcahuano' },
    { value: '8207', label: 'Tirúa' },
    { value: '8111', label: 'Tomé' },
    { value: '8420', label: 'Treguaco' },
    { value: '8312', label: 'Tucapel' },
    { value: '8313', label: 'Yumbel' },
    { value: '8421', label: 'Yungay' },
  ],
  // La Araucanía
  '9': [
    { value: '9201', label: 'Angol' },
    { value: '9102', label: 'Carahue' },
    { value: '9202', label: 'Collipulli' },
    { value: '9103', label: 'Cunco' },
    { value: '9203', label: 'Curacautín' },
    { value: '9104', label: 'Curarrehue' },
    { value: '9204', label: 'Ercilla' },
    { value: '9105', label: 'Freire' },
    { value: '9106', label: 'Galvarino' },
    { value: '9107', label: 'Gorbea' },
    { value: '9108', label: 'Lautaro' },
    { value: '9109', label: 'Loncoche' },
    { value: '9205', label: 'Lonquimay' },
    { value: '9206', label: 'Los Sauces' },
    { value: '9207', label: 'Lumaco' },
    { value: '9110', label: 'Melipeuco' },
    { value: '9111', label: 'Nueva Imperial' },
    { value: '9112', label: 'Padre Las Casas' },
    { value: '9113', label: 'Perquenco' },
    { value: '9114', label: 'Pitrufquén' },
    { value: '9115', label: 'Pucón' },
    { value: '9208', label: 'Purén' },
    { value: '9209', label: 'Renaico' },
    { value: '9116', label: 'Saavedra' },
    { value: '9101', label: 'Temuco' },
    { value: '9117', label: 'Teodoro Schmidt' },
    { value: '9118', label: 'Toltén' },
    { value: '9210', label: 'Traiguén' },
    { value: '9211', label: 'Victoria' },
    { value: '9119', label: 'Vilcún' },
    { value: '9120', label: 'Villarrica' },
  ],
  // Los Lagos
  '10': [
    { value: '10202', label: 'Ancud' },
    { value: '10102', label: 'Calbuco' },
    { value: '10201', label: 'Castro' },
    { value: '10401', label: 'Chaitén' },
    { value: '10203', label: 'Chonchi' },
    { value: '10103', label: 'Cochamó' },
    { value: '10204', label: 'Curaco de Vélez' },
    { value: '10205', label: 'Dalcahue' },
    { value: '10104', label: 'Fresia' },
    { value: '10105', label: 'Frutillar' },
    { value: '10402', label: 'Futaleufú' },
    { value: '10403', label: 'Hualaihué' },
    { value: '10107', label: 'Llanquihue' },
    { value: '10106', label: 'Los Muermos' },
    { value: '10108', label: 'Maullín' },
    { value: '10301', label: 'Osorno' },
    { value: '10404', label: 'Palena' },
    { value: '10101', label: 'Puerto Montt' },
    { value: '10302', label: 'Puerto Octay' },
    { value: '10109', label: 'Puerto Varas' },
    { value: '10206', label: 'Puqueldón' },
    { value: '10303', label: 'Purranque' },
    { value: '10304', label: 'Puyehue' },
    { value: '10207', label: 'Queilén' },
    { value: '10208', label: 'Quellón' },
    { value: '10209', label: 'Quemchi' },
    { value: '10210', label: 'Quinchao' },
    { value: '10305', label: 'Río Negro' },
    { value: '10306', label: 'San Juan de la Costa' },
    { value: '10307', label: 'San Pablo' },
  ],
  // Aysén
  '11': [
    { value: '11201', label: 'Aysén' },
    { value: '11401', label: 'Chile Chico' },
    { value: '11202', label: 'Cisnes' },
    { value: '11301', label: 'Cochrane' },
    { value: '11101', label: 'Coyhaique' },
    { value: '11203', label: 'Guaitecas' },
    { value: '11102', label: 'Lago Verde' },
    { value: '11302', label: 'O´Higgins' },
    { value: '11402', label: 'Río Ibáñez' },
    { value: '11303', label: 'Tortel' },
  ],
  // Magallanes
  '12': [
    { value: '12202', label: 'Antártica' },
    { value: '12102', label: 'Laguna Blanca' },
    { value: '12401', label: 'Natales' },
    { value: '12201', label: 'Navarino' },
    { value: '12301', label: 'Porvenir' },
    { value: '12302', label: 'Primavera' },
    { value: '12101', label: 'Punta Arenas' },
    { value: '12103', label: 'Río Verde' },
    { value: '12104', label: 'San Gregorio' },
    { value: '12303', label: 'Timaukel' },
    { value: '12402', label: 'Torres del Paine' },
  ],
  // Metropolitana
  '13': [
    { value: '13502', label: 'Alhué' },
    { value: '13402', label: 'Buin' },
    { value: '13403', label: 'Calera de Tango' },
    { value: '13102', label: 'Cerrillos' },
    { value: '13103', label: 'Cerro Navia' },
    { value: '13301', label: 'Colina' },
    { value: '13104', label: 'Conchalí' },
    { value: '13503', label: 'Curacaví' },
    { value: '13105', label: 'El Bosque' },
    { value: '13602', label: 'El Monte' },
    { value: '13106', label: 'Estación Central' },
    { value: '13107', label: 'Huechuraba' },
    { value: '13108', label: 'Independencia' },
    { value: '13603', label: 'Isla de Maipo' },
    { value: '13109', label: 'La Cisterna' },
    { value: '13110', label: 'La Florida' },
    { value: '13111', label: 'La Granja' },
    { value: '13112', label: 'La Pintana' },
    { value: '13113', label: 'La Reina' },
    { value: '13302', label: 'Lampa' },
    { value: '13114', label: 'Las Condes' },
    { value: '13115', label: 'Lo Barnechea' },
    { value: '13116', label: 'Lo Espejo' },
    { value: '13117', label: 'Lo Prado' },
    { value: '13118', label: 'Macul' },
    { value: '13119', label: 'Maipú' },
    { value: '13504', label: 'María Pinto' },
    { value: '13501', label: 'Melipilla' },
    { value: '13120', label: 'Ñuñoa' },
    { value: '13604', label: 'Padre Hurtado' },
    { value: '13404', label: 'Paine' },
    { value: '13121', label: 'Pedro Aguirre' },
    { value: '13605', label: 'Peñaflor' },
    { value: '13122', label: 'Peñalolén' },
    { value: '13202', label: 'Pirque' },
    { value: '13123', label: 'Providencia' },
    { value: '13124', label: 'Pudahuel' },
    { value: '13201', label: 'Puente Alto' },
    { value: '13125', label: 'Quilicura' },
    { value: '13126', label: 'Quinta Normal' },
    { value: '13127', label: 'Recoleta' },
    { value: '13128', label: 'Renca' },
    { value: '13401', label: 'San Bernardo' },
    { value: '13129', label: 'San Joaquín' },
    { value: '13203', label: 'San José de Maipo' },
    { value: '13130', label: 'San Miguel' },
    { value: '13505', label: 'San Pedro' },
    { value: '13131', label: 'San Ramón' },
    { value: '13101', label: 'Santiago' },
    { value: '13601', label: 'Talagante' },
    { value: '13303', label: 'Tiltil' },
    { value: '13132', label: 'Vitacura' },
    { value: '13999', label: 'Sin información' },
  ],
  // Los Ríos
  '14': [
    { value: '10502', label: 'Corral' },
    { value: '10503', label: 'Futrono' },
    { value: '10504', label: 'La Unión' },
    { value: '10505', label: 'Lago Ranco' },
    { value: '10506', label: 'Lanco' },
    { value: '10507', label: 'Los Lagos' },
    { value: '10508', label: 'Máfil' },
    { value: '10509', label: 'Mariquina' },
    { value: '10510', label: 'Paillaco' },
    { value: '10511', label: 'Panguipulli' },
    { value: '10512', label: 'Río Bueno' },
    { value: '10501', label: 'Valdivia' },
  ],
  // Arica y Parinacota
  '15': [
    { value: '1201', label: 'Arica' },
    { value: '1202', label: 'Camarones' },
    { value: '1302', label: 'General Lagos' },
    { value: '1301', label: 'Putre' },
  ],
};
